import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const bankFilters: PartnerFilter[] = [
  { key: "nz_bank", label: "NZ銀行" },
  { key: "multi_currency", label: "多通貨サービス" },
  { key: "app_service", label: "アプリ型サービス" },
  { key: "salary", label: "給与受取" },
  { key: "rent_payment", label: "家賃支払い" },
  { key: "money_transfer", label: "海外送金" },
  { key: "arrival", label: "到着直後" },
  { key: "long_stay", label: "長期滞在" },
  { key: "online_opening", label: "オンライン開設" },
  { key: "debit_card", label: "デビットカード" },
  { key: "branch_support", label: "支店サポート" },
  { key: "mobile_wallet", label: "Apple Pay / Google Pay" },
  { key: "no_monthly_fee", label: "月額手数料なし" },
];

export const bankComparisonFields: PartnerComparisonField[] = [
  { key: "isNzBank", label: "NZ銀行", important: true },
  { key: "multiCurrency", label: "多通貨対応", important: true },
  { key: "onlineOpening", label: "オンライン開設", important: true },
  { key: "localAddressRequired", label: "現地住所" },
  { key: "identityCheck", label: "本人確認" },
  { key: "debitCard", label: "デビットカード", important: true },
  { key: "mobileWallet", label: "Apple Pay / Google Pay" },
  { key: "salaryReceiving", label: "給与受取", important: true },
  { key: "rentPayment", label: "家賃支払い", important: true },
  { key: "moneyTransferFriendly", label: "海外送金相性" },
  { key: "appNote", label: "アプリ" },
  { key: "branchSupport", label: "支店サポート" },
  { key: "atmAccess", label: "ATM" },
  { key: "monthlyFeeNote", label: "月額手数料" },
];

export const bankRecommendations: PartnerRecommendation[] = [
  {
    title: "NZで給与を受け取りたい人",
    description:
      "現地で働く予定がある場合は、給与受取に使いやすいNZ銀行口座を比較すると安心です。",
    filterKey: "salary",
  },
  {
    title: "到着後すぐ生活費を管理したい人",
    description:
      "到着直後は、多通貨アプリやオンライン管理しやすいサービスを併用すると便利な場合があります。",
    filterKey: "arrival",
  },
  {
    title: "日本からNZへ送金したい人",
    description:
      "日本からNZへ生活費や初期費用を送る場合は、海外送金ページも合わせて確認してください。",
    filterKey: "money_transfer",
  },
  {
    title: "店舗サポートを重視する人",
    description:
      "対面サポートや支店での相談を重視する場合は、NZの大手銀行を比較してください。",
    filterKey: "branch_support",
  },
  {
    title: "アプリで管理したい人",
    description:
      "アプリで残高や送金を管理したい人は、オンライン機能やアプリの使いやすさを確認しましょう。",
    filterKey: "app_service",
  },
];

export const bankServices: PartnerService[] = [
  {
    id: "anz-new-zealand",
    category: "bank",
    name: "ANZ New Zealand",
    countryCode: "NZ",
    serviceType: "NZ Bank",
    shortDescription:
      "ニュージーランドの大手銀行。給与受取、家賃支払い、日常決済用の口座として比較しやすい選択肢です。",
    priceNote:
      "口座種類や利用条件により手数料が変わります。最新条件は公式サイトで確認してください。",
    keyFeatures: ["NZ大手銀行", "給与受取", "支店サポート"],
    recommendedFor: ["給与受取", "家賃支払い", "長期滞在", "店舗サポート"],
    cautions: [
      "口座開設には本人確認、ビザ、住所確認などが必要になる場合があります。",
      "オンライン開設の可否や必要書類は時期により変わる可能性があります。",
    ],
    comparison: {
      isNzBank: true,
      multiCurrency: false,
      onlineOpening: "depends",
      localAddressRequired: "depends",
      identityCheck: "パスポート、ビザ、住所確認などを確認",
      debitCard: true,
      mobileWallet: "depends",
      salaryReceiving: true,
      rentPayment: true,
      moneyTransferFriendly: "depends",
      appNote: "モバイルバンキングあり",
      branchSupport: true,
      atmAccess: "広い",
      monthlyFeeNote: "口座種類により異なる",
    },
    officialUrl: "https://www.anz.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-27",
    filterTags: [
      "nz_bank",
      "salary",
      "rent_payment",
      "long_stay",
      "debit_card",
      "branch_support",
      "mobile_wallet",
    ],
  },
  {
    id: "asb-bank",
    category: "bank",
    name: "ASB Bank",
    countryCode: "NZ",
    serviceType: "NZ Bank",
    shortDescription:
      "アプリやオンライン機能も確認しやすいNZ大手銀行。給与受取や生活費管理の候補になります。",
    priceNote:
      "口座種類、カード、利用条件により手数料が変わります。公式サイトで確認してください。",
    keyFeatures: ["NZ大手銀行", "アプリ管理", "給与受取"],
    recommendedFor: ["給与受取", "アプリ管理", "家賃支払い", "長期滞在"],
    cautions: [
      "開設条件はビザ、住所、本人確認状況によって変わる場合があります。",
      "渡航前にオンライン申請できるかは公式情報で確認してください。",
    ],
    comparison: {
      isNzBank: true,
      multiCurrency: false,
      onlineOpening: "depends",
      localAddressRequired: "depends",
      identityCheck: "パスポート、ビザ、住所確認などを確認",
      debitCard: true,
      mobileWallet: "depends",
      salaryReceiving: true,
      rentPayment: true,
      moneyTransferFriendly: "depends",
      appNote: "アプリ管理に対応",
      branchSupport: true,
      atmAccess: "広い",
      monthlyFeeNote: "口座種類により異なる",
    },
    officialUrl: "https://www.asb.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-27",
    filterTags: [
      "nz_bank",
      "salary",
      "rent_payment",
      "arrival",
      "long_stay",
      "online_opening",
      "debit_card",
      "branch_support",
      "mobile_wallet",
    ],
  },
  {
    id: "bnz",
    category: "bank",
    name: "BNZ",
    countryCode: "NZ",
    serviceType: "NZ Bank",
    shortDescription:
      "ニュージーランドの主要銀行。給与受取、家賃支払い、カード決済など現地生活用に比較できます。",
    priceNote:
      "口座タイプと条件により手数料が異なります。契約前に最新条件を確認してください。",
    keyFeatures: ["NZ銀行", "デビットカード", "支店サポート"],
    recommendedFor: ["給与受取", "家賃支払い", "長期滞在", "店舗サポート"],
    cautions: [
      "必要書類や住所確認の条件は公式サイトで確認してください。",
      "オンラインで完結できるかは申込条件により変わる場合があります。",
    ],
    comparison: {
      isNzBank: true,
      multiCurrency: false,
      onlineOpening: "depends",
      localAddressRequired: "depends",
      identityCheck: "本人確認、住所確認、ビザなどを確認",
      debitCard: true,
      mobileWallet: "depends",
      salaryReceiving: true,
      rentPayment: true,
      moneyTransferFriendly: "depends",
      appNote: "モバイルバンキングあり",
      branchSupport: true,
      atmAccess: "広い",
      monthlyFeeNote: "口座種類により異なる",
    },
    officialUrl: "https://www.bnz.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-27",
    filterTags: [
      "nz_bank",
      "salary",
      "rent_payment",
      "long_stay",
      "debit_card",
      "branch_support",
      "mobile_wallet",
    ],
  },
  {
    id: "westpac-new-zealand",
    category: "bank",
    name: "Westpac New Zealand",
    countryCode: "NZ",
    serviceType: "NZ Bank",
    shortDescription:
      "NZ大手銀行。現地生活の支払い、給与受取、支店相談を重視する人が比較しやすい銀行です。",
    priceNote:
      "手数料やカード条件は口座と利用状況により変わります。公式サイトで確認してください。",
    keyFeatures: ["NZ大手銀行", "給与受取", "支店あり"],
    recommendedFor: ["給与受取", "家賃支払い", "店舗サポート", "長期滞在"],
    cautions: [
      "本人確認や住所証明が必要になる場合があります。",
      "口座開設予約や来店の必要性は時期・地域で変わる場合があります。",
    ],
    comparison: {
      isNzBank: true,
      multiCurrency: false,
      onlineOpening: "depends",
      localAddressRequired: "depends",
      identityCheck: "本人確認、ビザ、住所確認などを確認",
      debitCard: true,
      mobileWallet: "depends",
      salaryReceiving: true,
      rentPayment: true,
      moneyTransferFriendly: "depends",
      appNote: "モバイルバンキングあり",
      branchSupport: true,
      atmAccess: "広い",
      monthlyFeeNote: "口座種類により異なる",
    },
    officialUrl: "https://www.westpac.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-27",
    filterTags: [
      "nz_bank",
      "salary",
      "rent_payment",
      "long_stay",
      "debit_card",
      "branch_support",
      "mobile_wallet",
    ],
  },
  {
    id: "kiwibank",
    category: "bank",
    name: "Kiwibank",
    countryCode: "NZ",
    serviceType: "NZ Bank",
    shortDescription:
      "ニュージーランドの銀行。現地生活用の口座、カード、日常決済の候補として比較できます。",
    priceNote:
      "口座種類や利用条件で手数料が変わります。最新条件は公式サイトで確認してください。",
    keyFeatures: ["NZ銀行", "日常口座", "カード"],
    recommendedFor: ["給与受取", "家賃支払い", "現地生活", "長期滞在"],
    cautions: [
      "利用できる支店・サポート範囲を事前に確認してください。",
      "開設条件や必要書類は変更される場合があります。",
    ],
    comparison: {
      isNzBank: true,
      multiCurrency: false,
      onlineOpening: "depends",
      localAddressRequired: "depends",
      identityCheck: "本人確認、住所確認、ビザなどを確認",
      debitCard: true,
      mobileWallet: "depends",
      salaryReceiving: true,
      rentPayment: true,
      moneyTransferFriendly: "depends",
      appNote: "アプリあり",
      branchSupport: true,
      atmAccess: "要確認",
      monthlyFeeNote: "口座種類により異なる",
    },
    officialUrl: "https://www.kiwibank.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-27",
    filterTags: [
      "nz_bank",
      "salary",
      "rent_payment",
      "long_stay",
      "debit_card",
      "branch_support",
      "mobile_wallet",
    ],
  },
  {
    id: "wise-account",
    category: "bank",
    name: "Wise",
    countryCode: "GLOBAL",
    serviceType: "Multi-currency / Transfer",
    shortDescription:
      "多通貨管理と海外送金に使いやすいサービス。日本からNZへの送金や到着直後の資金管理と相性があります。",
    priceNote:
      "両替・送金手数料は通貨、金額、支払方法により変わります。公式サイトで確認してください。",
    keyFeatures: ["多通貨", "海外送金", "アプリ管理"],
    recommendedFor: ["海外送金", "到着直後", "アプリ管理", "生活費管理"],
    cautions: [
      "NZ銀行口座そのものではありません。給与受取や雇用主側の条件は確認が必要です。",
      "カードや口座情報の提供条件は居住国・本人確認状況により変わる場合があります。",
    ],
    comparison: {
      isNzBank: false,
      multiCurrency: true,
      onlineOpening: true,
      localAddressRequired: "depends",
      identityCheck: "オンライン本人確認が必要",
      debitCard: "depends",
      mobileWallet: "depends",
      salaryReceiving: "depends",
      rentPayment: "depends",
      moneyTransferFriendly: true,
      appNote: "アプリで管理しやすい",
      branchSupport: false,
      atmAccess: "カード条件による",
      monthlyFeeNote: "要確認",
    },
    officialUrl: "https://wise.com/",
    isAffiliate: false,
    affiliateStatus: "official",
    affiliateNetwork: "Official",
    lastCheckedAt: "2026-06-27",
    filterTags: [
      "multi_currency",
      "app_service",
      "money_transfer",
      "arrival",
      "online_opening",
      "debit_card",
      "no_monthly_fee",
    ],
  },
  {
    id: "revolut",
    category: "bank",
    name: "Revolut",
    countryCode: "GLOBAL",
    serviceType: "Multi-currency / App",
    shortDescription:
      "アプリ中心で外貨管理やカード利用を確認できるサービス。旅行や到着直後の支払い管理に向いています。",
    priceNote:
      "無料・有料プラン、両替、カード、ATM条件は変わる場合があります。公式サイトで確認してください。",
    keyFeatures: ["アプリ型", "多通貨", "カード"],
    recommendedFor: ["アプリ管理", "到着直後", "旅行併用", "生活費管理"],
    cautions: [
      "NZ銀行口座ではありません。給与受取や家賃支払いで使えるかは相手側に確認してください。",
      "利用可能国、本人確認、カード発行条件は変更される場合があります。",
    ],
    comparison: {
      isNzBank: false,
      multiCurrency: true,
      onlineOpening: true,
      localAddressRequired: "depends",
      identityCheck: "オンライン本人確認が必要",
      debitCard: "depends",
      mobileWallet: "depends",
      salaryReceiving: "depends",
      rentPayment: "depends",
      moneyTransferFriendly: "depends",
      appNote: "アプリ中心",
      branchSupport: false,
      atmAccess: "プラン条件による",
      monthlyFeeNote: "無料/有料プランあり",
    },
    officialUrl: "https://www.revolut.com/",
    isAffiliate: false,
    affiliateStatus: "official",
    affiliateNetwork: "Official",
    lastCheckedAt: "2026-06-27",
    filterTags: [
      "multi_currency",
      "app_service",
      "money_transfer",
      "arrival",
      "online_opening",
      "debit_card",
      "mobile_wallet",
      "no_monthly_fee",
    ],
  },
];
