import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const electricityFilters: PartnerFilter[] = [
  { key: "flat", label: "フラット向け" },
  { key: "solo", label: "一人暮らし向け" },
  { key: "long_term", label: "長期滞在向け" },
  { key: "short_term", label: "短期滞在向け" },
  { key: "online", label: "オンライン申込" },
  { key: "app", label: "アプリ管理" },
  { key: "fixed_plan", label: "固定料金プラン" },
  { key: "variable_plan", label: "変動料金プラン" },
  { key: "no_exit_fee", label: "解約手数料なし" },
  { key: "renewable", label: "再生可能エネルギー配慮" },
];

export const electricityComparisonFields: PartnerComparisonField[] = [
  { key: "serviceArea", label: "提供エリア", important: true },
  { key: "baseChargeNote", label: "基本料金", important: true },
  { key: "usageRateNote", label: "電力量料金", important: true },
  { key: "fixedPlan", label: "固定料金" },
  { key: "variablePlan", label: "変動料金" },
  { key: "contractTermNote", label: "契約期間" },
  { key: "exitFeeNote", label: "解約手数料" },
  { key: "onlineApplication", label: "オンライン申込", important: true },
  { key: "appManagement", label: "アプリ管理" },
  { key: "paymentMethodsNote", label: "支払い方法" },
  { key: "movingSupport", label: "引っ越し" },
  { key: "flatFriendly", label: "フラット向き" },
  { key: "soloFriendly", label: "一人暮らし" },
  { key: "longStayFriendly", label: "長期滞在" },
  { key: "shortStayFriendly", label: "短期滞在" },
  { key: "renewableNote", label: "再エネ配慮" },
];

export const electricityRecommendations: PartnerRecommendation[] = [
  {
    title: "フラット生活向け",
    description:
      "複数人で住むフラットでは、請求の分かりやすさ、支払い方法、引っ越し手続きのしやすさを比較すると安心です。",
    filterKey: "flat",
  },
  {
    title: "一人暮らし向け",
    description:
      "一人暮らしでは、基本料金、使用量に応じた料金、アプリ管理のしやすさを確認しましょう。",
    filterKey: "solo",
  },
  {
    title: "オンライン管理したい人向け",
    description:
      "アプリやオンラインで使用量や請求を確認したい人は、オンライン管理機能を比較すると便利です。",
    filterKey: "app",
  },
  {
    title: "長期滞在向け",
    description:
      "長期で住む予定がある場合は、契約条件や解約手数料、支払い方法を含めて確認しましょう。",
    filterKey: "long_term",
  },
  {
    title: "料金を比較したい人向け",
    description:
      "電気料金は地域や使用量によって変わるため、契約前に公式サイトで最新料金を確認してください。",
    filterKey: "variable_plan",
  },
];

export const electricityServices: PartnerService[] = [
  {
    id: "contact-energy",
    category: "electricity",
    name: "Contact Energy",
    countryCode: "NZ",
    serviceType: "Major Retailer",
    shortDescription:
      "NZ大手の電力会社。電気、ガス、インターネットなども含めて確認できます。",
    priceNote: "住所、住居タイプ、使用量、プランにより変わります。",
    keyFeatures: ["大手", "複数サービス", "引っ越し手続き"],
    recommendedFor: ["フラット生活", "長期滞在", "まとめて管理したい人"],
    cautions: [
      "住所ごとの料金、契約期間、解約条件を公式サイトで確認してください。",
      "キャンペーン条件は時期により変わる場合があります。",
    ],
    comparison: {
      serviceArea: "NZ広域",
      baseChargeNote: "住所・プランによる",
      usageRateNote: "使用量・地域による",
      fixedPlan: "depends",
      variablePlan: "depends",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      onlineApplication: true,
      appManagement: true,
      paymentMethodsNote: "カード/口座振替等を確認",
      movingSupport: true,
      flatFriendly: true,
      soloFriendly: true,
      longStayFriendly: true,
      shortStayFriendly: "depends",
      renewableNote: "再エネ関連情報あり",
    },
    officialUrl: "https://contact.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "online", "app", "fixed_plan"],
  },
  {
    id: "mercury",
    category: "electricity",
    name: "Mercury",
    countryCode: "NZ",
    serviceType: "Major Retailer",
    shortDescription:
      "電気、ガス、通信などを確認できるNZ大手サービスです。",
    priceNote: "住所とプラン、キャンペーン条件で変わります。",
    keyFeatures: ["大手", "アプリ管理", "オンライン申込"],
    recommendedFor: ["フラット生活", "オンライン管理", "長期滞在"],
    cautions: [
      "キャンペーン、契約期間、解約手数料の条件を確認してください。",
    ],
    comparison: {
      serviceArea: "NZ広域",
      baseChargeNote: "住所・プランによる",
      usageRateNote: "使用量・地域による",
      fixedPlan: "depends",
      variablePlan: "depends",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      onlineApplication: true,
      appManagement: true,
      paymentMethodsNote: "カード/口座振替等を確認",
      movingSupport: true,
      flatFriendly: true,
      soloFriendly: true,
      longStayFriendly: true,
      shortStayFriendly: "depends",
      renewableNote: "再エネ関連情報あり",
    },
    officialUrl: "https://www.mercury.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "online", "app", "fixed_plan"],
  },
  {
    id: "genesis-energy",
    category: "electricity",
    name: "Genesis Energy",
    countryCode: "NZ",
    serviceType: "Major Retailer",
    shortDescription:
      "家庭向けプランを確認しやすいNZ大手の電力会社です。",
    priceNote: "地域、住居、契約条件で変わります。",
    keyFeatures: ["大手", "家庭向け", "オンライン管理"],
    recommendedFor: ["フラット生活", "長期滞在", "一人暮らし"],
    cautions: ["料金プラン、契約期間、解約条件を比較してください。"],
    comparison: {
      serviceArea: "NZ広域",
      baseChargeNote: "住所・プランによる",
      usageRateNote: "使用量・地域による",
      fixedPlan: "depends",
      variablePlan: "depends",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      onlineApplication: true,
      appManagement: true,
      paymentMethodsNote: "カード/口座振替等を確認",
      movingSupport: true,
      flatFriendly: true,
      soloFriendly: true,
      longStayFriendly: true,
      shortStayFriendly: "depends",
      renewableNote: "要確認",
    },
    officialUrl: "https://www.genesisenergy.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "online", "app", "fixed_plan"],
  },
  {
    id: "electric-kiwi",
    category: "electricity",
    name: "Electric Kiwi",
    countryCode: "NZ",
    serviceType: "Online-focused",
    shortDescription:
      "オンライン管理や料金の見やすさを重視したい人が確認しやすい電力会社です。",
    priceNote: "住所、利用時間帯、プランにより変わります。",
    keyFeatures: ["オンライン", "アプリ管理", "料金比較"],
    recommendedFor: ["一人暮らし", "フラット生活", "料金を比較したい人"],
    cautions: [
      "時間帯別の条件や最新プランを公式サイトで確認してください。",
    ],
    comparison: {
      serviceArea: "提供エリア要確認",
      baseChargeNote: "住所・プランによる",
      usageRateNote: "使用時間帯で変わる場合あり",
      fixedPlan: "depends",
      variablePlan: true,
      contractTermNote: "要確認",
      exitFeeNote: "要確認",
      onlineApplication: true,
      appManagement: true,
      paymentMethodsNote: "オンライン支払い中心",
      movingSupport: true,
      flatFriendly: true,
      soloFriendly: true,
      longStayFriendly: true,
      shortStayFriendly: "depends",
      renewableNote: "要確認",
    },
    officialUrl: "https://www.electrickiwi.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "flat",
      "solo",
      "long_term",
      "short_term",
      "online",
      "app",
      "variable_plan",
    ],
  },
  {
    id: "flick-electric",
    category: "electricity",
    name: "Flick Electric",
    countryCode: "NZ",
    serviceType: "Budget / Flexible",
    shortDescription:
      "市場連動型など、料金の仕組みを細かく比較したい人向けに確認できます。",
    priceNote: "市場価格、住所、使用量により変動します。",
    keyFeatures: ["変動料金", "オンライン", "使用量確認"],
    recommendedFor: ["料金を比較したい人", "一人暮らし", "アプリ管理"],
    cautions: [
      "価格変動リスク、請求条件、対応エリアを確認してください。",
    ],
    comparison: {
      serviceArea: "提供エリア要確認",
      baseChargeNote: "住所・プランによる",
      usageRateNote: "市場価格で変動する場合あり",
      fixedPlan: false,
      variablePlan: true,
      contractTermNote: "要確認",
      exitFeeNote: "要確認",
      onlineApplication: true,
      appManagement: true,
      paymentMethodsNote: "オンライン支払い中心",
      movingSupport: "depends",
      flatFriendly: "depends",
      soloFriendly: true,
      longStayFriendly: true,
      shortStayFriendly: "depends",
      renewableNote: "要確認",
    },
    officialUrl: "https://www.flickelectric.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["solo", "online", "app", "variable_plan"],
  },
  {
    id: "powershop",
    category: "electricity",
    name: "Powershop",
    countryCode: "NZ",
    serviceType: "Online-focused",
    shortDescription:
      "アプリやオンラインで電気代を管理したい人向けに確認できます。",
    priceNote: "地域、使用量、プランで変わります。",
    keyFeatures: ["アプリ", "オンライン管理", "料金確認"],
    recommendedFor: ["オンライン管理", "一人暮らし", "フラット生活"],
    cautions: ["プラン内容、支払い条件、提供エリアを確認してください。"],
    comparison: {
      serviceArea: "提供エリア要確認",
      baseChargeNote: "住所・プランによる",
      usageRateNote: "使用量・地域による",
      fixedPlan: "depends",
      variablePlan: "depends",
      contractTermNote: "要確認",
      exitFeeNote: "要確認",
      onlineApplication: true,
      appManagement: true,
      paymentMethodsNote: "オンライン支払い中心",
      movingSupport: true,
      flatFriendly: true,
      soloFriendly: true,
      longStayFriendly: true,
      shortStayFriendly: "depends",
      renewableNote: "要確認",
    },
    officialUrl: "https://www.powershop.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "online", "app", "variable_plan"],
  },
  {
    id: "frank-energy",
    category: "electricity",
    name: "Frank Energy",
    countryCode: "NZ",
    serviceType: "Budget / Flexible",
    shortDescription:
      "シンプルな料金やオンライン手続きを確認したい人向けの電力サービスです。",
    priceNote: "住所、使用量、契約条件で変わります。",
    keyFeatures: ["シンプル", "オンライン", "料金比較"],
    recommendedFor: ["一人暮らし", "料金を比較したい人", "短期滞在"],
    cautions: ["提供エリア、解約条件、支払い方法を確認してください。"],
    comparison: {
      serviceArea: "提供エリア要確認",
      baseChargeNote: "住所・プランによる",
      usageRateNote: "使用量・地域による",
      fixedPlan: "depends",
      variablePlan: "depends",
      contractTermNote: "要確認",
      exitFeeNote: "要確認",
      onlineApplication: true,
      appManagement: "depends",
      paymentMethodsNote: "要確認",
      movingSupport: "depends",
      flatFriendly: "depends",
      soloFriendly: true,
      longStayFriendly: true,
      shortStayFriendly: "depends",
      renewableNote: "要確認",
    },
    officialUrl: "https://www.frankenergy.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["solo", "short_term", "online", "variable_plan"],
  },
  {
    id: "nova-energy",
    category: "electricity",
    name: "Nova Energy",
    countryCode: "NZ",
    serviceType: "Major Retailer",
    shortDescription:
      "電気、ガス、ブロードバンドなどをまとめて確認できるNZのエネルギー会社です。",
    priceNote: "住所、プラン、セット契約条件で変わります。",
    keyFeatures: ["電気", "ガス", "ブロードバンド"],
    recommendedFor: ["長期滞在", "まとめて管理", "フラット生活"],
    cautions: ["セット契約の条件、契約期間、解約手数料を確認してください。"],
    comparison: {
      serviceArea: "提供エリア要確認",
      baseChargeNote: "住所・プランによる",
      usageRateNote: "使用量・地域による",
      fixedPlan: "depends",
      variablePlan: "depends",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      onlineApplication: true,
      appManagement: "depends",
      paymentMethodsNote: "カード/口座振替等を確認",
      movingSupport: true,
      flatFriendly: true,
      soloFriendly: true,
      longStayFriendly: true,
      shortStayFriendly: "depends",
      renewableNote: "要確認",
    },
    officialUrl: "https://www.novaenergy.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "online", "fixed_plan"],
  },
];
