import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const furnitureFilters: PartnerFilter[] = [
  { key: "arrival", label: "到着直後" },
  { key: "budget", label: "安さ重視" },
  { key: "used", label: "中古" },
  { key: "long_stay", label: "長期滞在" },
  { key: "flat", label: "フラット向け" },
  { key: "study_work", label: "勉強・仕事向け" },
  { key: "bedding", label: "寝具" },
  { key: "kitchenware", label: "キッチン用品" },
  { key: "furniture", label: "家具" },
  { key: "appliances", label: "家電" },
  { key: "storage", label: "収納用品" },
  { key: "office", label: "文具・仕事用品" },
  { key: "delivery", label: "配送あり" },
  { key: "stores", label: "店舗あり" },
  { key: "used_purchase", label: "中古購入" },
  { key: "new_purchase", label: "新品購入" },
];

export const furnitureComparisonFields: PartnerComparisonField[] = [
  { key: "newItems", label: "新品", important: true },
  { key: "usedItems", label: "中古", important: true },
  { key: "priceRangeNote", label: "価格帯", important: true },
  { key: "storeAvailabilityNote", label: "店舗数" },
  { key: "deliveryAvailable", label: "配送対応", important: true },
  { key: "bedding", label: "寝具" },
  { key: "kitchenware", label: "キッチン用品" },
  { key: "furniture", label: "家具" },
  { key: "appliances", label: "家電" },
  { key: "storage", label: "収納用品" },
  { key: "studyWorkItems", label: "学習・仕事用品" },
  { key: "arrivalFriendly", label: "到着直後向き" },
  { key: "longStayFriendly", label: "長期滞在向き" },
  { key: "flatFriendly", label: "フラット向き" },
];

export const furnitureRecommendations: PartnerRecommendation[] = [
  {
    title: "到着直後に最低限そろえたい人向け",
    description:
      "寝具、タオル、キッチン用品など、到着直後に必要なものを手早く揃えたい場合に比較したい候補です。",
    filterKey: "arrival",
  },
  {
    title: "安くそろえたい人向け",
    description:
      "費用を抑えたい場合は、新品の低価格ショップと中古マーケットを組み合わせるとよい場合があります。",
    filterKey: "budget",
  },
  {
    title: "中古で探したい人向け",
    description:
      "家具や家電を安く探したい場合は、中古マーケットが選択肢になります。ただし受け渡しや状態確認には注意してください。",
    filterKey: "used",
  },
  {
    title: "長期滞在向け",
    description:
      "長期滞在では、価格だけでなく品質、配送、返品条件も確認すると安心です。",
    filterKey: "long_stay",
  },
  {
    title: "勉強・仕事環境を整えたい人向け",
    description:
      "履歴書作成、オンライン面接、学習用に机・椅子・文具・周辺機器を整えたい人向けです。",
    filterKey: "study_work",
  },
];

export const furnitureServices: PartnerService[] = [
  {
    id: "kmart-nz",
    category: "furniture",
    name: "Kmart NZ",
    countryCode: "NZ",
    serviceType: "New / Budget",
    shortDescription:
      "寝具、タオル、キッチン用品、収納用品を低価格でそろえやすい大型小売店です。",
    priceNote: "低価格帯が中心。商品、店舗、在庫状況で変わります。",
    keyFeatures: ["低価格", "寝具", "生活用品"],
    recommendedFor: ["到着直後", "安さ重視", "一人暮らし"],
    cautions: ["大型家具や人気商品の在庫は店舗ごとに確認してください。"],
    comparison: {
      newItems: true,
      usedItems: false,
      priceRangeNote: "低〜中",
      storeAvailabilityNote: "主要都市に店舗あり",
      deliveryAvailable: "depends",
      bedding: true,
      kitchenware: true,
      furniture: true,
      appliances: "depends",
      storage: true,
      studyWorkItems: true,
      arrivalFriendly: true,
      longStayFriendly: true,
      flatFriendly: true,
    },
    officialUrl: "https://www.kmart.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "arrival",
      "budget",
      "long_stay",
      "flat",
      "study_work",
      "bedding",
      "kitchenware",
      "furniture",
      "storage",
      "office",
      "stores",
      "new_purchase",
    ],
  },
  {
    id: "the-warehouse",
    category: "furniture",
    name: "The Warehouse",
    countryCode: "NZ",
    serviceType: "New / Budget",
    shortDescription:
      "生活用品、家具、家電、寝具を幅広く確認できる総合小売店です。",
    priceNote: "低〜中価格帯。セールや在庫で変動します。",
    keyFeatures: ["総合小売", "店舗多め", "家具・家電"],
    recommendedFor: ["到着直後", "長期滞在", "フラット生活"],
    cautions: ["大型商品の配送条件、返品条件、在庫状況を確認してください。"],
    comparison: {
      newItems: true,
      usedItems: false,
      priceRangeNote: "低〜中",
      storeAvailabilityNote: "NZ各地に店舗あり",
      deliveryAvailable: true,
      bedding: true,
      kitchenware: true,
      furniture: true,
      appliances: true,
      storage: true,
      studyWorkItems: true,
      arrivalFriendly: true,
      longStayFriendly: true,
      flatFriendly: true,
    },
    officialUrl: "https://www.thewarehouse.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "arrival",
      "budget",
      "long_stay",
      "flat",
      "study_work",
      "bedding",
      "kitchenware",
      "furniture",
      "appliances",
      "storage",
      "office",
      "delivery",
      "stores",
      "new_purchase",
    ],
  },
  {
    id: "briscoes",
    category: "furniture",
    name: "Briscoes",
    countryCode: "NZ",
    serviceType: "New / Home Goods",
    shortDescription:
      "寝具、タオル、キッチン用品、家庭用品をセール時に確認しやすい店舗です。",
    priceNote: "中価格帯が中心。セール時期で大きく変わります。",
    keyFeatures: ["寝具", "キッチン用品", "セール"],
    recommendedFor: ["到着直後", "長期滞在", "品質も見たい人"],
    cautions: ["定価とセール価格、配送条件を比較して確認してください。"],
    comparison: {
      newItems: true,
      usedItems: false,
      priceRangeNote: "中",
      storeAvailabilityNote: "主要都市に店舗あり",
      deliveryAvailable: true,
      bedding: true,
      kitchenware: true,
      furniture: "depends",
      appliances: "depends",
      storage: true,
      studyWorkItems: false,
      arrivalFriendly: true,
      longStayFriendly: true,
      flatFriendly: true,
    },
    officialUrl: "https://www.briscoes.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "arrival",
      "long_stay",
      "flat",
      "bedding",
      "kitchenware",
      "storage",
      "delivery",
      "stores",
      "new_purchase",
    ],
  },
  {
    id: "ikea-nz",
    category: "furniture",
    name: "IKEA",
    countryCode: "NZ",
    serviceType: "New / Home Goods",
    shortDescription:
      "家具、収納、寝具を新品でそろえたい場合に確認したい選択肢です。",
    priceNote: "商品と配送条件で変わります。",
    keyFeatures: ["家具", "収納", "長期滞在"],
    recommendedFor: ["長期滞在", "勉強・仕事環境", "新品家具"],
    cautions: ["NZでの受け取り、配送、在庫、返品条件を確認してください。"],
    comparison: {
      newItems: true,
      usedItems: false,
      priceRangeNote: "中",
      storeAvailabilityNote: "地域により限定的",
      deliveryAvailable: true,
      bedding: true,
      kitchenware: true,
      furniture: true,
      appliances: "depends",
      storage: true,
      studyWorkItems: true,
      arrivalFriendly: "depends",
      longStayFriendly: true,
      flatFriendly: true,
    },
    officialUrl: "https://www.ikea.com/nz/en/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "long_stay",
      "flat",
      "study_work",
      "bedding",
      "kitchenware",
      "furniture",
      "storage",
      "office",
      "delivery",
      "new_purchase",
    ],
  },
  {
    id: "trade-me",
    category: "furniture",
    name: "Trade Me",
    countryCode: "NZ",
    serviceType: "Used Marketplace",
    shortDescription:
      "NZで中古家具、家電、生活用品を探しやすいマーケットプレイスです。",
    priceNote: "出品者、地域、状態、受け渡し条件で大きく変わります。",
    keyFeatures: ["中古", "個人売買", "幅広い"],
    recommendedFor: ["安さ重視", "中古家具", "長期滞在"],
    cautions: [
      "商品の状態、受け渡し場所、支払い方法、安全性を必ず確認してください。",
    ],
    comparison: {
      newItems: "depends",
      usedItems: true,
      priceRangeNote: "低〜高",
      storeAvailabilityNote: "オンライン",
      deliveryAvailable: "depends",
      bedding: "depends",
      kitchenware: true,
      furniture: true,
      appliances: true,
      storage: true,
      studyWorkItems: true,
      arrivalFriendly: "depends",
      longStayFriendly: true,
      flatFriendly: true,
    },
    officialUrl: "https://www.trademe.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "budget",
      "used",
      "long_stay",
      "flat",
      "study_work",
      "kitchenware",
      "furniture",
      "appliances",
      "storage",
      "office",
      "used_purchase",
    ],
  },
  {
    id: "facebook-marketplace",
    category: "furniture",
    name: "Facebook Marketplace",
    countryCode: "GLOBAL",
    serviceType: "Used Marketplace",
    shortDescription:
      "近隣エリアで中古家具、家電、生活用品を探せる個人売買マーケットです。",
    priceNote: "出品者、交渉、状態、受け渡し方法で変わります。",
    keyFeatures: ["中古", "近隣検索", "個人売買"],
    recommendedFor: ["安さ重視", "中古", "近場で探したい人"],
    cautions: [
      "取引相手、受け渡し場所、支払い方法、安全性を慎重に確認してください。",
    ],
    comparison: {
      newItems: "depends",
      usedItems: true,
      priceRangeNote: "低〜高",
      storeAvailabilityNote: "オンライン",
      deliveryAvailable: "depends",
      bedding: "depends",
      kitchenware: true,
      furniture: true,
      appliances: true,
      storage: true,
      studyWorkItems: true,
      arrivalFriendly: "depends",
      longStayFriendly: true,
      flatFriendly: true,
    },
    officialUrl: "https://www.facebook.com/marketplace/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "budget",
      "used",
      "long_stay",
      "flat",
      "study_work",
      "kitchenware",
      "furniture",
      "appliances",
      "storage",
      "office",
      "used_purchase",
    ],
  },
  {
    id: "mitre-10",
    category: "furniture",
    name: "Mitre 10",
    countryCode: "NZ",
    serviceType: "DIY / Hardware",
    shortDescription:
      "工具、収納、DIY用品、屋外用品、生活まわりの補修用品を確認できます。",
    priceNote: "商品、店舗、配送条件で変わります。",
    keyFeatures: ["DIY", "収納", "工具"],
    recommendedFor: ["長期滞在", "フラット生活", "補修・収納"],
    cautions: ["賃貸物件では、取り付けや補修の可否を管理者に確認してください。"],
    comparison: {
      newItems: true,
      usedItems: false,
      priceRangeNote: "中",
      storeAvailabilityNote: "NZ各地に店舗あり",
      deliveryAvailable: true,
      bedding: false,
      kitchenware: "depends",
      furniture: "depends",
      appliances: "depends",
      storage: true,
      studyWorkItems: "depends",
      arrivalFriendly: "depends",
      longStayFriendly: true,
      flatFriendly: true,
    },
    officialUrl: "https://www.mitre10.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "long_stay",
      "flat",
      "storage",
      "delivery",
      "stores",
      "new_purchase",
    ],
  },
  {
    id: "warehouse-stationery",
    category: "furniture",
    name: "Warehouse Stationery",
    countryCode: "NZ",
    serviceType: "Office / Study",
    shortDescription:
      "文具、プリント、学習用品、仕事用の周辺機器を確認できます。",
    priceNote: "商品、店舗、セールで変わります。",
    keyFeatures: ["文具", "学習用品", "仕事環境"],
    recommendedFor: ["勉強・仕事環境", "履歴書作成", "オンライン面接"],
    cautions: ["大型家具は限定的なため、机や椅子は他サービスも比較してください。"],
    comparison: {
      newItems: true,
      usedItems: false,
      priceRangeNote: "低〜中",
      storeAvailabilityNote: "主要都市に店舗あり",
      deliveryAvailable: true,
      bedding: false,
      kitchenware: false,
      furniture: "depends",
      appliances: "depends",
      storage: "depends",
      studyWorkItems: true,
      arrivalFriendly: "depends",
      longStayFriendly: true,
      flatFriendly: true,
    },
    officialUrl: "https://www.warehousestationery.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: [
      "study_work",
      "office",
      "delivery",
      "stores",
      "new_purchase",
    ],
  },
];
