import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const insuranceFilters: PartnerFilter[] = [
  { key: "working_holiday", label: "ワーホリ" },
  { key: "study", label: "留学" },
  { key: "travel", label: "旅行" },
  { key: "nomad", label: "ノマド" },
  { key: "age_18_30", label: "18-30" },
  { key: "age_31_39", label: "31-39" },
  { key: "age_40_plus", label: "40+" },
  { key: "medical_1m", label: "医療100万以上" },
  { key: "medical_3m", label: "医療300万以上" },
  { key: "medical_unlimited", label: "医療無制限" },
  { key: "sports_yes", label: "スポーツ補償あり" },
  { key: "sports_no", label: "スポーツ補償なし" },
  { key: "japanese_yes", label: "日本語サポートあり" },
  { key: "japanese_no", label: "日本語サポートなし" },
  { key: "online_claim_yes", label: "オンライン請求あり" },
  { key: "online_claim_no", label: "オンライン請求なし" },
];

export const insuranceComparisonFields: PartnerComparisonField[] = [
  { key: "workingHoliday", label: "ワーホリ対応", important: true },
  { key: "travel", label: "旅行対応" },
  { key: "medical", label: "医療費補償", important: true },
  { key: "belongings", label: "携行品補償" },
  { key: "liability", label: "賠償責任" },
  { key: "dental", label: "歯科補償" },
  { key: "sports", label: "スポーツ補償" },
  { key: "homeVisit", label: "一時帰国" },
  { key: "joinTiming", label: "加入可能タイミング", important: true },
  { key: "japanese", label: "日本語サポート" },
  { key: "support24h", label: "24時間サポート" },
  { key: "onlineClaim", label: "オンライン請求" },
];

export const insuranceRecommendations: PartnerRecommendation[] = [
  {
    title: "ワーホリ向けに確認したい",
    description:
      "長期滞在、医療費、携行品、加入タイミングをまとめて確認したい人向けです。",
    filterKey: "working_holiday",
  },
  {
    title: "短期旅行・到着直後向け",
    description:
      "旅行保険として使いやすいか、短期の医療補償や携行品補償を確認したい人向けです。",
    filterKey: "travel",
  },
  {
    title: "長期滞在・ノマド向け",
    description:
      "月額型や渡航後加入、海外滞在中の継続しやすさを見たい人向けです。",
    filterKey: "nomad",
  },
  {
    title: "スポーツ・アクティビティ向け",
    description:
      "ハイキング、スキー、マリンスポーツなどを予定している人向けです。",
    filterKey: "sports_yes",
  },
];

export const insuranceServices: PartnerService[] = [
  {
    id: "safetywing",
    category: "insurance",
    name: "SafetyWing",
    countryCode: "GLOBAL",
    serviceType: "海外医療保険",
    shortDescription:
      "月額型で海外滞在中の医療補償を確認しやすいサービスです。",
    priceNote: "月額型。年齢、居住国、補償条件で変わります。",
    keyFeatures: ["月額型", "海外滞在向け", "渡航後加入も確認可"],
    recommendedFor: ["長期滞在", "ノマド", "オンライン完結"],
    cautions: [
      "携行品、賠償責任、歯科補償は条件を必ず確認してください。",
      "ワーホリビザ要件を満たすか公式サイトで確認してください。",
    ],
    comparison: {
      workingHoliday: "要確認",
      travel: true,
      medical: "上限あり",
      belongings: "要確認",
      liability: "要確認",
      dental: "限定的",
      sports: "一部対象外あり",
      homeVisit: "要確認",
      joinTiming: "渡航前/渡航後",
      japanese: false,
      support24h: true,
      onlineClaim: true,
    },
    officialUrl: "https://www.safetywing.com/",
    isAffiliate: false,
    affiliateStatus: "official",
    lastCheckedAt: "2026-06-25",
    filterTags: [
      "working_holiday",
      "travel",
      "nomad",
      "age_18_30",
      "age_31_39",
      "age_40_plus",
      "medical_1m",
      "online_claim_yes",
      "japanese_no",
      "sports_yes",
    ],
  },
  {
    id: "world-nomads",
    category: "insurance",
    name: "World Nomads",
    countryCode: "GLOBAL",
    serviceType: "旅行保険",
    shortDescription:
      "旅行やアクティビティを含む海外滞在向けの保険を比較できます。",
    priceNote: "滞在期間、補償範囲、居住国で変わります。",
    keyFeatures: ["旅行向け", "アクティビティ", "オンライン見積"],
    recommendedFor: ["短期旅行", "アクティビティ", "複数国移動"],
    cautions: [
      "加入条件は居住国により異なります。",
      "危険スポーツ、既往症、携行品の条件を確認してください。",
    ],
    comparison: {
      workingHoliday: "要確認",
      travel: true,
      medical: "プランによる",
      belongings: true,
      liability: true,
      dental: "要確認",
      sports: "比較的強い",
      homeVisit: "要確認",
      joinTiming: "渡航前/渡航後",
      japanese: false,
      support24h: true,
      onlineClaim: true,
    },
    officialUrl: "https://www.worldnomads.com/",
    isAffiliate: false,
    affiliateStatus: "official",
    lastCheckedAt: "2026-06-25",
    filterTags: [
      "working_holiday",
      "travel",
      "age_18_30",
      "age_31_39",
      "age_40_plus",
      "medical_1m",
      "sports_yes",
      "online_claim_yes",
      "japanese_no",
    ],
  },
  {
    id: "genki",
    category: "insurance",
    name: "Genki",
    countryCode: "GLOBAL",
    serviceType: "海外医療保険",
    shortDescription:
      "海外在住者や長期滞在者向けの医療保険を確認できます。",
    priceNote: "月額目安。年齢やプランにより変わります。",
    keyFeatures: ["長期向け", "医療補償", "オンライン管理"],
    recommendedFor: ["長期滞在", "医療重視", "ノマド"],
    cautions: [
      "旅行保険ではなく医療保険寄りの条件を確認してください。",
      "携行品や賠償責任は別途確認が必要です。",
    ],
    comparison: {
      workingHoliday: "要確認",
      travel: "要確認",
      medical: "高額補償",
      belongings: "要確認",
      liability: "要確認",
      dental: "一部",
      sports: "要確認",
      homeVisit: "要確認",
      joinTiming: "渡航前/渡航後",
      japanese: false,
      support24h: true,
      onlineClaim: true,
    },
    officialUrl: "https://genki.world/",
    isAffiliate: false,
    affiliateStatus: "official",
    lastCheckedAt: "2026-06-25",
    filterTags: [
      "working_holiday",
      "nomad",
      "age_18_30",
      "age_31_39",
      "age_40_plus",
      "medical_3m",
      "online_claim_yes",
      "japanese_no",
      "sports_yes",
    ],
  },
  {
    id: "allianz-travel",
    category: "insurance",
    name: "Allianz Travel",
    countryCode: "GLOBAL",
    serviceType: "旅行保険",
    shortDescription:
      "大手保険グループの旅行保険。出発国や地域別に商品を確認できます。",
    priceNote: "国、期間、補償内容により異なります。",
    keyFeatures: ["大手保険", "旅行保険", "地域別プラン"],
    recommendedFor: ["大手ブランド重視", "旅行", "医療補償"],
    cautions: [
      "申込国によって商品が異なります。",
      "ワーホリ用途で使えるか公式サイトで確認してください。",
    ],
    comparison: {
      workingHoliday: "要確認",
      travel: true,
      medical: "プランによる",
      belongings: true,
      liability: true,
      dental: "要確認",
      sports: "要確認",
      homeVisit: "要確認",
      joinTiming: "渡航前中心",
      japanese: "国により異なる",
      support24h: true,
      onlineClaim: "要確認",
    },
    officialUrl: "https://www.allianztravelinsurance.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-25",
    filterTags: [
      "travel",
      "age_18_30",
      "age_31_39",
      "age_40_plus",
      "medical_1m",
      "sports_yes",
      "japanese_yes",
      "online_claim_yes",
    ],
  },
  {
    id: "cover-more",
    category: "insurance",
    name: "Cover-More",
    countryCode: "GLOBAL",
    serviceType: "旅行保険",
    shortDescription:
      "旅行や長期滞在向けの補償を国別に確認できる保険サービスです。",
    priceNote: "出発国、旅行期間、補償範囲で変わります。",
    keyFeatures: ["旅行保険", "医療補償", "24時間サポート"],
    recommendedFor: ["旅行", "長期滞在", "サポート重視"],
    cautions: [
      "居住国や出発地によって加入できる商品が異なります。",
      "ワーホリでの就労中補償は条件確認が必要です。",
    ],
    comparison: {
      workingHoliday: "要確認",
      travel: true,
      medical: "プランによる",
      belongings: true,
      liability: true,
      dental: "要確認",
      sports: "要確認",
      homeVisit: "要確認",
      joinTiming: "渡航前中心",
      japanese: "要確認",
      support24h: true,
      onlineClaim: true,
    },
    officialUrl: "https://www.covermore.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-25",
    filterTags: [
      "travel",
      "working_holiday",
      "age_18_30",
      "age_31_39",
      "age_40_plus",
      "medical_1m",
      "sports_yes",
      "online_claim_yes",
      "japanese_no",
    ],
  },
  {
    id: "southern-cross-travel",
    category: "insurance",
    name: "Southern Cross Travel Insurance",
    countryCode: "NZ",
    serviceType: "旅行保険",
    shortDescription:
      "NZ大手の旅行保険。NZ発着や地域条件を確認できます。",
    priceNote: "旅行先、期間、補償範囲で変わります。",
    keyFeatures: ["NZ大手", "旅行保険", "オンライン見積"],
    recommendedFor: ["NZブランド重視", "旅行", "医療補償"],
    cautions: [
      "居住国や出発地の条件を確認してください。",
      "ワーホリ長期滞在で使えるか確認してください。",
    ],
    comparison: {
      workingHoliday: "要確認",
      travel: true,
      medical: "プランによる",
      belongings: true,
      liability: true,
      dental: "要確認",
      sports: "要確認",
      homeVisit: "要確認",
      joinTiming: "渡航前中心",
      japanese: false,
      support24h: true,
      onlineClaim: true,
    },
    officialUrl: "https://www.scti.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-25",
    filterTags: [
      "travel",
      "age_18_30",
      "age_31_39",
      "age_40_plus",
      "medical_1m",
      "sports_yes",
      "online_claim_yes",
      "japanese_no",
    ],
  },
  {
    id: "orbitprotect",
    category: "insurance",
    name: "OrbitProtect",
    countryCode: "NZ",
    serviceType: "NZ向け保険",
    shortDescription:
      "ニュージーランド滞在者向けの保険プランを確認できます。",
    priceNote: "滞在期間と補償内容で変わります。",
    keyFeatures: ["NZ向け", "学生/訪問者向け", "期間指定"],
    recommendedFor: ["NZ滞在", "ワーホリ", "留学"],
    cautions: [
      "対象ビザや補償条件を確認してください。",
      "日本語対応の有無は公式確認が必要です。",
    ],
    comparison: {
      workingHoliday: true,
      travel: "要確認",
      medical: "あり",
      belongings: "要確認",
      liability: "要確認",
      dental: "要確認",
      sports: "要確認",
      homeVisit: "要確認",
      joinTiming: "渡航前中心",
      japanese: "要確認",
      support24h: "要確認",
      onlineClaim: "要確認",
    },
    officialUrl: "https://orbitprotect.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-25",
    filterTags: [
      "working_holiday",
      "study",
      "age_18_30",
      "age_31_39",
      "medical_1m",
      "sports_yes",
      "japanese_yes",
      "online_claim_yes",
    ],
  },
  {
    id: "uni-care",
    category: "insurance",
    name: "Uni-Care",
    countryCode: "NZ",
    serviceType: "留学・訪問者保険",
    shortDescription:
      "NZ留学や訪問者向けの保険を確認できるサービスです。",
    priceNote: "滞在期間、ビザ、補償内容で変わります。",
    keyFeatures: ["留学向け", "NZ向け", "訪問者保険"],
    recommendedFor: ["留学", "長期滞在", "NZ滞在"],
    cautions: [
      "ワーホリ用途で利用できるか公式サイトで確認してください。",
      "スポーツや就労中の補償条件を確認してください。",
    ],
    comparison: {
      workingHoliday: "要確認",
      travel: "要確認",
      medical: "あり",
      belongings: "要確認",
      liability: "要確認",
      dental: "要確認",
      sports: "要確認",
      homeVisit: "要確認",
      joinTiming: "渡航前中心",
      japanese: "要確認",
      support24h: "要確認",
      onlineClaim: "要確認",
    },
    officialUrl: "https://www.uni-care.org/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-25",
    filterTags: [
      "study",
      "working_holiday",
      "age_18_30",
      "age_31_39",
      "medical_1m",
      "sports_yes",
      "japanese_yes",
      "online_claim_yes",
    ],
  },
];
