import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const insuranceFilters: PartnerFilter[] = [
  { key: "long_term", label: "長期向け" },
  { key: "budget", label: "安さ重視" },
  { key: "medical", label: "医療補償重視" },
  { key: "japanese_support", label: "日本語対応" },
  { key: "working_holiday", label: "ワーホリ向け" },
];

export const insuranceComparisonFields: PartnerComparisonField[] = [
  { key: "price", label: "保険料目安", important: true },
  { key: "medical", label: "医療補償", important: true },
  { key: "belongings", label: "携行品" },
  { key: "liability", label: "賠償責任" },
  { key: "dental", label: "歯科" },
  { key: "homeVisit", label: "一時帰国" },
  { key: "workingHoliday", label: "ワーホリ" },
  { key: "activities", label: "スポーツ" },
  { key: "cashless", label: "キャッシュレス" },
  { key: "japanese", label: "日本語" },
  { key: "joinTiming", label: "加入タイミング" },
];

export const insuranceRecommendations: PartnerRecommendation[] = [
  { title: "とにかく安く備えたい人向け", description: "月額型や必要最低限の補償から比較したい人向けです。", filterKey: "budget" },
  { title: "医療補償を重視したい人向け", description: "病気やケガの治療費を優先して確認したい人向けです。", filterKey: "medical" },
  { title: "長期ワーホリ向け", description: "半年から1年程度の滞在で継続しやすい保険を見たい人向けです。", filterKey: "long_term" },
  { title: "日本語サポート重視", description: "問い合わせや緊急時の安心感を重視したい人向けです。", filterKey: "japanese_support" },
];

export const insuranceServices: PartnerService[] = [
  {
    id: "safetywing",
    category: "insurance",
    name: "SafetyWing",
    countryCode: "GLOBAL",
    serviceType: "海外医療保険",
    shortDescription: "月額型で海外滞在中の医療補償を確認しやすいサービスです。",
    priceNote: "月額型の目安料金。年齢や補償条件で変わります。",
    keyFeatures: ["月額型", "海外滞在向け", "オンライン加入"],
    recommendedFor: ["安さ重視", "長期滞在", "オンライン完結"],
    cautions: ["携行品や歯科などは条件を確認してください。", "ワーホリ要件を満たすか公式情報で確認してください。"],
    comparison: { price: "月額型", medical: "あり", belongings: "要確認", liability: "要確認", dental: "限定的", homeVisit: "要確認", workingHoliday: true, activities: "一部対象外あり", cashless: "要確認", japanese: false, joinTiming: "渡航前/渡航後" },
    officialUrl: "https://www.safetywing.com/",
    isAffiliate: false,
    lastCheckedAt: "2026-06-23",
    filterTags: ["budget", "long_term", "medical", "working_holiday"],
  },
  {
    id: "world-nomads",
    category: "insurance",
    name: "World Nomads",
    countryCode: "GLOBAL",
    serviceType: "旅行保険",
    shortDescription: "旅行やアクティビティを含む海外滞在向けの保険を比較できます。",
    priceNote: "滞在期間、補償範囲、居住国で変わります。",
    keyFeatures: ["旅行向け", "アクティビティ対応", "オンライン見積"],
    recommendedFor: ["旅行とワーホリ兼用", "アクティビティ重視"],
    cautions: ["加入条件は居住国により異なります。", "既往症や危険スポーツの扱いを確認してください。"],
    comparison: { price: "見積確認", medical: "あり", belongings: "あり", liability: "あり", dental: "要確認", homeVisit: "要確認", workingHoliday: "要確認", activities: "比較的強い", cashless: "要確認", japanese: false, joinTiming: "渡航前/渡航後" },
    officialUrl: "https://www.worldnomads.com/",
    isAffiliate: false,
    lastCheckedAt: "2026-06-23",
    filterTags: ["medical", "working_holiday"],
  },
  {
    id: "allianz-partners",
    category: "insurance",
    name: "Allianz Partners",
    countryCode: "GLOBAL",
    serviceType: "旅行保険",
    shortDescription: "大手保険グループの旅行保険。補償内容を地域別に確認できます。",
    priceNote: "国、期間、補償内容により異なります。",
    keyFeatures: ["大手保険", "旅行保険", "地域別プラン"],
    recommendedFor: ["医療補償重視", "大手ブランド重視"],
    cautions: ["申込国によって商品が異なります。", "ワーホリ用途で使えるか確認してください。"],
    comparison: { price: "見積確認", medical: "あり", belongings: "あり", liability: "あり", dental: "要確認", homeVisit: "要確認", workingHoliday: "要確認", activities: "要確認", cashless: "要確認", japanese: "国により異なる", joinTiming: "渡航前中心" },
    officialUrl: "https://www.allianz-partners.com/",
    isAffiliate: false,
    lastCheckedAt: "2026-06-23",
    filterTags: ["medical"],
  },
  {
    id: "genki",
    category: "insurance",
    name: "Genki",
    countryCode: "GLOBAL",
    serviceType: "海外医療保険",
    shortDescription: "海外在住者や長期滞在者向けの医療保険を確認できます。",
    priceNote: "月額目安。年齢やプランにより変わります。",
    keyFeatures: ["長期向け", "医療補償", "オンライン管理"],
    recommendedFor: ["長期ワーホリ", "医療補償重視"],
    cautions: ["旅行保険ではなく医療保険寄りの条件を確認してください。", "携行品補償は別途確認が必要です。"],
    comparison: { price: "月額型", medical: "あり", belongings: "要確認", liability: "要確認", dental: "一部", homeVisit: "要確認", workingHoliday: true, activities: "要確認", cashless: "要確認", japanese: false, joinTiming: "渡航前/渡航後" },
    officialUrl: "https://genki.world/",
    isAffiliate: false,
    lastCheckedAt: "2026-06-23",
    filterTags: ["long_term", "medical", "working_holiday"],
  },
  {
    id: "orbitprotect",
    category: "insurance",
    name: "OrbitProtect",
    countryCode: "NZ",
    serviceType: "NZ向け保険",
    shortDescription: "ニュージーランド滞在者向けの保険プランを確認できます。",
    priceNote: "滞在期間と補償内容で変わります。",
    keyFeatures: ["NZ向け", "学生/訪問者向け", "期間指定"],
    recommendedFor: ["NZ滞在", "ワーホリ向け"],
    cautions: ["対象ビザや補償条件を確認してください。", "日本語対応の有無は公式確認が必要です。"],
    comparison: { price: "見積確認", medical: "あり", belongings: "要確認", liability: "要確認", dental: "要確認", homeVisit: "要確認", workingHoliday: true, activities: "要確認", cashless: "要確認", japanese: "要確認", joinTiming: "渡航前中心" },
    officialUrl: "https://orbitprotect.com/",
    isAffiliate: false,
    lastCheckedAt: "2026-06-23",
    filterTags: ["working_holiday", "medical"],
  },
  {
    id: "southern-cross-travel",
    category: "insurance",
    name: "Southern Cross Travel Insurance",
    countryCode: "NZ",
    serviceType: "旅行保険",
    shortDescription: "NZ大手の旅行保険。NZ発着や地域条件を確認できます。",
    priceNote: "旅行先、期間、補償範囲で変わります。",
    keyFeatures: ["NZ大手", "旅行保険", "オンライン見積"],
    recommendedFor: ["医療補償重視", "NZブランド重視"],
    cautions: ["居住国や出発地の条件を確認してください。", "ワーホリ長期滞在で使えるか確認してください。"],
    comparison: { price: "見積確認", medical: "あり", belongings: "あり", liability: "あり", dental: "要確認", homeVisit: "要確認", workingHoliday: "要確認", activities: "要確認", cashless: "要確認", japanese: false, joinTiming: "渡航前中心" },
    officialUrl: "https://www.scti.co.nz/",
    isAffiliate: false,
    lastCheckedAt: "2026-06-23",
    filterTags: ["medical"],
  },
];
