import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const internetFilters: PartnerFilter[] = [
  { key: "flat", label: "フラット向け" },
  { key: "solo", label: "一人暮らし向け" },
  { key: "short_term", label: "短期滞在向け" },
  { key: "long_term", label: "長期滞在向け" },
  { key: "power_bundle", label: "電気セット向け" },
  { key: "fibre", label: "光回線" },
  { key: "wireless", label: "ワイヤレス" },
  { key: "unlimited", label: "データ無制限" },
  { key: "no_contract", label: "契約期間なし" },
  { key: "online", label: "オンライン申込" },
  { key: "app", label: "アプリ管理" },
  { key: "bundle_discount", label: "セット割あり" },
];

export const internetComparisonFields: PartnerComparisonField[] = [
  { key: "serviceArea", label: "提供エリア", important: true },
  { key: "fibreAvailable", label: "光回線", important: true },
  { key: "wirelessAvailable", label: "ワイヤレス" },
  { key: "unlimitedData", label: "無制限", important: true },
  { key: "monthlyPriceNote", label: "月額目安", important: true },
  { key: "contractTermNote", label: "契約期間" },
  { key: "exitFeeNote", label: "解約手数料" },
  { key: "routerCostNote", label: "ルーター費用" },
  { key: "setupTimeNote", label: "開通目安" },
  { key: "onlineApplication", label: "オンライン申込" },
  { key: "appManagement", label: "アプリ管理" },
  { key: "powerBundle", label: "電気セット" },
  { key: "flatFriendly", label: "フラット向き" },
  { key: "soloFriendly", label: "一人暮らし" },
  { key: "shortStayFriendly", label: "短期滞在" },
  { key: "longStayFriendly", label: "長期滞在" },
];

export const internetRecommendations: PartnerRecommendation[] = [
  {
    title: "フラット生活向け",
    description:
      "複数人で住むフラットでは、データ無制限、回線速度、支払いの分かりやすさを比較すると安心です。",
    filterKey: "flat",
  },
  {
    title: "一人暮らし向け",
    description:
      "一人暮らしでは、月額料金、契約期間、開通のしやすさを確認しましょう。",
    filterKey: "solo",
  },
  {
    title: "電気とまとめたい人向け",
    description:
      "電気とインターネットをまとめたい場合は、セット割や請求の管理しやすさを比較すると便利です。",
    filterKey: "power_bundle",
  },
  {
    title: "短期滞在向け",
    description:
      "短期滞在では、契約期間や解約条件、工事不要で使えるかを確認しましょう。",
    filterKey: "short_term",
  },
  {
    title: "長期滞在向け",
    description:
      "長期滞在では、回線速度、安定性、契約期間、ルーター費用を含めて比較すると安心です。",
    filterKey: "long_term",
  },
];

export const internetServices: PartnerService[] = [
  {
    id: "spark-internet",
    category: "internet",
    name: "Spark",
    countryCode: "NZ",
    serviceType: "Major Provider",
    shortDescription:
      "NZ大手の通信会社。光回線、ワイヤレスブロードバンド、モバイルとの組み合わせを確認できます。",
    priceNote: "住所、回線種別、契約条件、セット契約で変わります。",
    keyFeatures: ["大手", "光回線", "ワイヤレス"],
    recommendedFor: ["フラット生活", "長期滞在", "速度重視"],
    cautions: [
      "住所で利用できる回線、契約期間、ルーター費用を確認してください。",
    ],
    comparison: {
      serviceArea: "NZ広域",
      fibreAvailable: true,
      wirelessAvailable: true,
      unlimitedData: true,
      monthlyPriceNote: "住所・プランによる",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      routerCostNote: "要確認",
      setupTimeNote: "住所・回線状況による",
      onlineApplication: true,
      appManagement: true,
      powerBundle: false,
      flatFriendly: true,
      soloFriendly: true,
      shortStayFriendly: "depends",
      longStayFriendly: true,
    },
    officialUrl: "https://www.spark.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "fibre", "wireless", "unlimited", "online", "app"],
  },
  {
    id: "one-nz-internet",
    category: "internet",
    name: "One NZ",
    countryCode: "NZ",
    serviceType: "Major Provider",
    shortDescription:
      "固定ブロードバンド、ワイヤレス、モバイルとの組み合わせを確認できます。",
    priceNote: "住所、回線、契約条件で変わります。",
    keyFeatures: ["大手", "光回線", "ワイヤレス"],
    recommendedFor: ["フラット生活", "長期滞在", "短期検討"],
    cautions: ["契約期間、解約条件、住所での提供可否を確認してください。"],
    comparison: {
      serviceArea: "NZ広域",
      fibreAvailable: true,
      wirelessAvailable: true,
      unlimitedData: true,
      monthlyPriceNote: "住所・プランによる",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      routerCostNote: "要確認",
      setupTimeNote: "住所・回線状況による",
      onlineApplication: true,
      appManagement: true,
      powerBundle: false,
      flatFriendly: true,
      soloFriendly: true,
      shortStayFriendly: "depends",
      longStayFriendly: true,
    },
    officialUrl: "https://one.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "short_term", "long_term", "fibre", "wireless", "unlimited", "online", "app"],
  },
  {
    id: "2degrees-internet",
    category: "internet",
    name: "2degrees",
    countryCode: "NZ",
    serviceType: "Major Provider",
    shortDescription:
      "光回線、ワイヤレス、モバイルや電気との組み合わせを確認できます。",
    priceNote: "プラン、住所、セット割、契約条件で変わります。",
    keyFeatures: ["光回線", "ワイヤレス", "セット割"],
    recommendedFor: ["フラット生活", "一人暮らし", "電気セット"],
    cautions: ["キャンペーン条件、セット割、契約期間を確認してください。"],
    comparison: {
      serviceArea: "NZ広域",
      fibreAvailable: true,
      wirelessAvailable: true,
      unlimitedData: true,
      monthlyPriceNote: "住所・プランによる",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      routerCostNote: "要確認",
      setupTimeNote: "住所・回線状況による",
      onlineApplication: true,
      appManagement: true,
      powerBundle: true,
      flatFriendly: true,
      soloFriendly: true,
      shortStayFriendly: "depends",
      longStayFriendly: true,
    },
    officialUrl: "https://www.2degrees.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "power_bundle", "fibre", "wireless", "unlimited", "online", "app", "bundle_discount"],
  },
  {
    id: "skinny-internet",
    category: "internet",
    name: "Skinny",
    countryCode: "NZ",
    serviceType: "Budget / Value",
    shortDescription:
      "シンプルで比較的低価格なブロードバンドやワイヤレスプランを確認できます。",
    priceNote: "プラン、回線種別、住所で変わります。",
    keyFeatures: ["低価格", "シンプル", "ワイヤレス"],
    recommendedFor: ["一人暮らし", "短期滞在", "料金重視"],
    cautions: ["サポート体制、契約条件、提供エリアを確認してください。"],
    comparison: {
      serviceArea: "提供エリア要確認",
      fibreAvailable: true,
      wirelessAvailable: true,
      unlimitedData: true,
      monthlyPriceNote: "比較的低めのプランあり",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      routerCostNote: "要確認",
      setupTimeNote: "ワイヤレスは始めやすい場合あり",
      onlineApplication: true,
      appManagement: "depends",
      powerBundle: false,
      flatFriendly: true,
      soloFriendly: true,
      shortStayFriendly: true,
      longStayFriendly: true,
    },
    officialUrl: "https://www.skinny.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "short_term", "long_term", "fibre", "wireless", "unlimited", "online", "no_contract"],
  },
  {
    id: "slingshot",
    category: "internet",
    name: "Slingshot",
    countryCode: "NZ",
    serviceType: "Power Bundle",
    shortDescription:
      "家庭向けブロードバンドや電気との組み合わせも確認できます。",
    priceNote: "住所、回線、セット条件で変わります。",
    keyFeatures: ["ブロードバンド", "電気セット", "無制限"],
    recommendedFor: ["フラット生活", "長期滞在", "電気セット"],
    cautions: ["セット割、契約期間、ルーター費用を確認してください。"],
    comparison: {
      serviceArea: "提供エリア要確認",
      fibreAvailable: true,
      wirelessAvailable: "depends",
      unlimitedData: true,
      monthlyPriceNote: "住所・プランによる",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      routerCostNote: "要確認",
      setupTimeNote: "住所・回線状況による",
      onlineApplication: true,
      appManagement: "depends",
      powerBundle: true,
      flatFriendly: true,
      soloFriendly: true,
      shortStayFriendly: "depends",
      longStayFriendly: true,
    },
    officialUrl: "https://www.slingshot.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "power_bundle", "fibre", "unlimited", "online", "bundle_discount"],
  },
  {
    id: "orcon",
    category: "internet",
    name: "Orcon",
    countryCode: "NZ",
    serviceType: "Fibre Broadband",
    shortDescription:
      "速度やデータ無制限を重視する住居向けに確認できます。",
    priceNote: "住所、速度、契約条件で変わります。",
    keyFeatures: ["光回線", "無制限", "速度"],
    recommendedFor: ["フラット生活", "長期滞在", "速度重視"],
    cautions: ["利用住所での回線対応、契約期間、ルーター費用を確認してください。"],
    comparison: {
      serviceArea: "提供エリア要確認",
      fibreAvailable: true,
      wirelessAvailable: false,
      unlimitedData: true,
      monthlyPriceNote: "住所・プランによる",
      contractTermNote: "プランによる",
      exitFeeNote: "要確認",
      routerCostNote: "要確認",
      setupTimeNote: "住所・回線状況による",
      onlineApplication: true,
      appManagement: "depends",
      powerBundle: false,
      flatFriendly: true,
      soloFriendly: true,
      shortStayFriendly: "depends",
      longStayFriendly: true,
    },
    officialUrl: "https://www.orcon.net.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["flat", "solo", "long_term", "fibre", "unlimited", "online"],
  },
  {
    id: "contact-broadband",
    category: "internet",
    name: "Contact Broadband",
    countryCode: "NZ",
    serviceType: "Power Bundle",
    shortDescription:
      "Contact Energyの電気とあわせてブロードバンドを確認できます。",
    priceNote: "住所、電気との組み合わせ、契約条件で変わります。",
    keyFeatures: ["電気セット", "ブロードバンド", "請求管理"],
    recommendedFor: ["電気セット", "一人暮らし", "長期滞在"],
    cautions: ["電気とのセット条件、契約期間、解約条件を確認してください。"],
    comparison: {
      serviceArea: "提供エリア要確認",
      fibreAvailable: true,
      wirelessAvailable: "depends",
      unlimitedData: "depends",
      monthlyPriceNote: "住所・セット条件による",
      contractTermNote: "要確認",
      exitFeeNote: "要確認",
      routerCostNote: "要確認",
      setupTimeNote: "住所・回線状況による",
      onlineApplication: true,
      appManagement: true,
      powerBundle: true,
      flatFriendly: "depends",
      soloFriendly: true,
      shortStayFriendly: "depends",
      longStayFriendly: true,
    },
    officialUrl: "https://contact.co.nz/broadband",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["solo", "long_term", "power_bundle", "fibre", "online", "app", "bundle_discount"],
  },
  {
    id: "mercury-broadband",
    category: "internet",
    name: "Mercury Broadband",
    countryCode: "NZ",
    serviceType: "Power Bundle",
    shortDescription:
      "Mercuryの電気契約とあわせてインターネットを確認できます。",
    priceNote: "住所、セット契約、キャンペーン条件で変わります。",
    keyFeatures: ["電気セット", "ブロードバンド", "オンライン管理"],
    recommendedFor: ["電気セット", "一人暮らし", "長期滞在"],
    cautions: ["セット割、契約期間、解約手数料を確認してください。"],
    comparison: {
      serviceArea: "提供エリア要確認",
      fibreAvailable: true,
      wirelessAvailable: "depends",
      unlimitedData: "depends",
      monthlyPriceNote: "住所・セット条件による",
      contractTermNote: "要確認",
      exitFeeNote: "要確認",
      routerCostNote: "要確認",
      setupTimeNote: "住所・回線状況による",
      onlineApplication: true,
      appManagement: true,
      powerBundle: true,
      flatFriendly: "depends",
      soloFriendly: true,
      shortStayFriendly: "depends",
      longStayFriendly: true,
    },
    officialUrl: "https://www.mercury.co.nz/broadband",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["solo", "long_term", "power_bundle", "fibre", "online", "app", "bundle_discount"],
  },
];
