import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const languageSchoolFilters: PartnerFilter[] = [
  { key: "beginner", label: "初心者向け" },
  { key: "ielts", label: "IELTS対策" },
  { key: "work_support", label: "仕事サポート" },
  { key: "japanese_support", label: "日本語サポート" },
  { key: "international", label: "多国籍環境" },
  { key: "short_term", label: "短期向け" },
  { key: "long_term", label: "長期向け" },
  { key: "auckland", label: "Auckland" },
  { key: "christchurch", label: "Christchurch" },
  { key: "wellington", label: "Wellington" },
  { key: "queenstown", label: "Queenstown" },
];

export const languageSchoolComparisonFields: PartnerComparisonField[] = [
  { key: "city", label: "都市", important: true },
  { key: "generalEnglish", label: "一般英語", important: true },
  { key: "ielts", label: "IELTS対策", important: true },
  { key: "businessEnglish", label: "ビジネス英語" },
  { key: "shortCourse", label: "短期コース" },
  { key: "longCourse", label: "長期コース" },
  { key: "japaneseSupport", label: "日本語サポート" },
  { key: "jobSupport", label: "仕事探しサポート" },
  { key: "accommodationSupport", label: "滞在先サポート" },
  { key: "activities", label: "アクティビティ" },
  { key: "priceNote", label: "学費目安", important: true },
  { key: "beginnerFriendly", label: "初心者向き" },
  { key: "internationalEnvironment", label: "多国籍環境" },
];

export const languageSchoolRecommendations: PartnerRecommendation[] = [
  {
    title: "英語初心者向け",
    description:
      "一般英語、生活立ち上げ、サポート体制を重視したい人向けの候補です。",
    filterKey: "beginner",
  },
  {
    title: "IELTS対策向け",
    description:
      "IELTSや試験対策コースの有無、開始日、レベル条件を比較したい人向けです。",
    filterKey: "ielts",
  },
  {
    title: "仕事探しも重視する人向け",
    description:
      "履歴書、面接、仕事探しのサポートがあるか確認したい人向けです。",
    filterKey: "work_support",
  },
  {
    title: "多国籍環境を重視する人向け",
    description:
      "国籍バランスや交流機会を重視し、英語環境に慣れたい人向けです。",
    filterKey: "international",
  },
  {
    title: "短期集中向け",
    description:
      "到着直後の短期間で英語に慣れたい人や、仕事探し前に準備したい人向けです。",
    filterKey: "short_term",
  },
];

export const languageSchoolServices: PartnerService[] = [
  {
    id: "languages-international",
    category: "language_school",
    name: "Languages International",
    countryCode: "NZ",
    serviceType: "Language School",
    shortDescription:
      "Auckland中心部で一般英語、IELTS、ビジネス英語などを確認できる語学学校です。",
    priceNote: "コース、週数、時期、教材費、滞在先手配で変わります。",
    keyFeatures: ["Auckland", "IELTS", "多国籍環境"],
    recommendedFor: ["IELTS対策", "多国籍環境", "長期学習"],
    cautions: ["開講コース、入学日、学費、滞在先費用を公式サイトで確認してください。"],
    comparison: {
      city: "Auckland",
      generalEnglish: true,
      ielts: true,
      businessEnglish: true,
      shortCourse: true,
      longCourse: true,
      japaneseSupport: "depends",
      jobSupport: "depends",
      accommodationSupport: true,
      activities: true,
      priceNote: "要見積",
      beginnerFriendly: true,
      internationalEnvironment: true,
    },
    officialUrl: "https://www.languages.ac.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["beginner", "ielts", "international", "short_term", "long_term", "auckland"],
  },
  {
    id: "nzlc",
    category: "language_school",
    name: "NZLC",
    countryCode: "NZ",
    serviceType: "Language School",
    shortDescription:
      "一般英語、IELTS、進学準備、サポート体制を確認できるNZの語学学校です。",
    priceNote: "コース、週数、入学時期で変わります。",
    keyFeatures: ["一般英語", "IELTS", "サポート"],
    recommendedFor: ["英語初心者", "仕事探し準備", "日本語サポート重視"],
    cautions: ["日本語サポート、仕事サポート、国籍比率は時期で変わる場合があります。"],
    comparison: {
      city: "Auckland",
      generalEnglish: true,
      ielts: true,
      businessEnglish: "depends",
      shortCourse: true,
      longCourse: true,
      japaneseSupport: true,
      jobSupport: true,
      accommodationSupport: true,
      activities: true,
      priceNote: "要見積",
      beginnerFriendly: true,
      internationalEnvironment: true,
    },
    officialUrl: "https://nzlc.ac.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["beginner", "ielts", "work_support", "japanese_support", "international", "short_term", "long_term", "auckland"],
  },
  {
    id: "worldwide-school",
    category: "language_school",
    name: "Worldwide School of English",
    countryCode: "NZ",
    serviceType: "Language School",
    shortDescription:
      "Aucklandで一般英語、試験対策、アクティビティ、滞在先サポートを確認できます。",
    priceNote: "コース、期間、滞在先手配で変わります。",
    keyFeatures: ["Auckland", "一般英語", "仕事準備"],
    recommendedFor: ["英語初心者", "仕事探し準備", "短期学習"],
    cautions: ["コース開始日、費用内訳、サポート内容を確認してください。"],
    comparison: {
      city: "Auckland",
      generalEnglish: true,
      ielts: "depends",
      businessEnglish: "depends",
      shortCourse: true,
      longCourse: true,
      japaneseSupport: "depends",
      jobSupport: true,
      accommodationSupport: true,
      activities: true,
      priceNote: "要見積",
      beginnerFriendly: true,
      internationalEnvironment: true,
    },
    officialUrl: "https://www.worldwideschoolofenglish.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["beginner", "work_support", "international", "short_term", "long_term", "auckland"],
  },
  {
    id: "kaplan-international-languages",
    category: "language_school",
    name: "Kaplan International Languages",
    countryCode: "NZ",
    serviceType: "Language School",
    shortDescription:
      "グローバル展開の語学学校。一般英語、試験対策、多国籍環境を確認できます。",
    priceNote: "都市、期間、コース、時期で変わります。",
    keyFeatures: ["グローバル", "IELTS", "多国籍環境"],
    recommendedFor: ["IELTS対策", "多国籍環境", "長期学習"],
    cautions: ["NZで提供中の校舎、コース、入学条件を公式サイトで確認してください。"],
    comparison: {
      city: "Auckland",
      generalEnglish: true,
      ielts: true,
      businessEnglish: true,
      shortCourse: true,
      longCourse: true,
      japaneseSupport: "depends",
      jobSupport: "depends",
      accommodationSupport: true,
      activities: true,
      priceNote: "要見積",
      beginnerFriendly: true,
      internationalEnvironment: true,
    },
    officialUrl: "https://www.kaplaninternational.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["beginner", "ielts", "international", "short_term", "long_term", "auckland"],
  },
  {
    id: "ec-english",
    category: "language_school",
    name: "EC English",
    countryCode: "NZ",
    serviceType: "Language School",
    shortDescription:
      "世界各地で展開する語学学校。一般英語、仕事準備、多国籍環境を確認できます。",
    priceNote: "都市、期間、コースで変わります。",
    keyFeatures: ["一般英語", "多国籍環境", "仕事準備"],
    recommendedFor: ["仕事探し準備", "多国籍環境", "短期集中"],
    cautions: ["NZでの開講状況、校舎、ビザ条件を公式サイトで確認してください。"],
    comparison: {
      city: "Auckland",
      generalEnglish: true,
      ielts: "depends",
      businessEnglish: true,
      shortCourse: true,
      longCourse: true,
      japaneseSupport: "depends",
      jobSupport: true,
      accommodationSupport: true,
      activities: true,
      priceNote: "要見積",
      beginnerFriendly: true,
      internationalEnvironment: true,
    },
    officialUrl: "https://www.ecenglish.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["beginner", "work_support", "international", "short_term", "long_term", "auckland"],
  },
  {
    id: "lsi-auckland",
    category: "language_school",
    name: "LSI Auckland",
    countryCode: "NZ",
    serviceType: "Language School",
    shortDescription:
      "Aucklandで一般英語、IELTS、短期・長期コースを確認できる語学学校です。",
    priceNote: "期間、コース、滞在先手配で変わります。",
    keyFeatures: ["Auckland", "IELTS", "短期集中"],
    recommendedFor: ["IELTS対策", "短期集中", "初心者"],
    cautions: ["コース内容、開始日、費用内訳、滞在先条件を確認してください。"],
    comparison: {
      city: "Auckland",
      generalEnglish: true,
      ielts: true,
      businessEnglish: "depends",
      shortCourse: true,
      longCourse: true,
      japaneseSupport: "depends",
      jobSupport: "depends",
      accommodationSupport: true,
      activities: true,
      priceNote: "要見積",
      beginnerFriendly: true,
      internationalEnvironment: true,
    },
    officialUrl: "https://www.lsi.edu/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["beginner", "ielts", "international", "short_term", "long_term", "auckland"],
  },
  {
    id: "auckland-english-academy",
    category: "language_school",
    name: "Auckland English Academy",
    countryCode: "NZ",
    serviceType: "Language School",
    shortDescription:
      "Aucklandで一般英語や短期コースを確認しやすい語学学校です。",
    priceNote: "コース、期間、入学時期で変わります。",
    keyFeatures: ["Auckland", "一般英語", "短期"],
    recommendedFor: ["英語初心者", "短期集中", "Auckland滞在"],
    cautions: ["コース内容、レベル、サポート範囲、学費を確認してください。"],
    comparison: {
      city: "Auckland",
      generalEnglish: true,
      ielts: "depends",
      businessEnglish: "depends",
      shortCourse: true,
      longCourse: "depends",
      japaneseSupport: "depends",
      jobSupport: "depends",
      accommodationSupport: "depends",
      activities: "depends",
      priceNote: "要見積",
      beginnerFriendly: true,
      internationalEnvironment: "depends",
    },
    officialUrl: "https://www.english.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["beginner", "short_term", "auckland"],
  },
  {
    id: "ccel",
    category: "language_school",
    name: "CCEL",
    countryCode: "NZ",
    serviceType: "Language School",
    shortDescription:
      "Christchurchを中心に一般英語、試験対策、滞在先サポートを確認できます。",
    priceNote: "コース、週数、滞在先手配で変わります。",
    keyFeatures: ["Christchurch", "一般英語", "短期・長期"],
    recommendedFor: ["短期集中", "長期学習", "Christchurch滞在"],
    cautions: ["都市、コース、開始日、滞在先条件を公式サイトで確認してください。"],
    comparison: {
      city: "Christchurch",
      generalEnglish: true,
      ielts: "depends",
      businessEnglish: "depends",
      shortCourse: true,
      longCourse: true,
      japaneseSupport: "depends",
      jobSupport: "depends",
      accommodationSupport: true,
      activities: true,
      priceNote: "要見積",
      beginnerFriendly: true,
      internationalEnvironment: true,
    },
    officialUrl: "https://ccel.co.nz/",
    isAffiliate: false,
    affiliateStatus: "none",
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["beginner", "short_term", "long_term", "international", "christchurch"],
  },
];
