import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const moneyTransferFilters: PartnerFilter[] = [
  { key: "country_nz", label: "ニュージーランド" },
  { key: "country_au", label: "オーストラリア" },
  { key: "country_ca", label: "カナダ" },
  { key: "purpose_living", label: "生活費" },
  { key: "purpose_initial", label: "初期費用" },
  { key: "purpose_rent", label: "家賃" },
  { key: "purpose_tuition", label: "学費" },
  { key: "purpose_family", label: "仕送り" },
  { key: "speed_same_day", label: "即日" },
  { key: "speed_one_day", label: "1営業日" },
  { key: "speed_few_days", label: "数営業日" },
  { key: "japanese_support", label: "日本語対応あり" },
  { key: "app", label: "アプリ対応あり" },
];

export const moneyTransferComparisonFields: PartnerComparisonField[] = [
  { key: "coverage", label: "対応国", important: true },
  { key: "jpToNz", label: "日本→NZ", important: true },
  { key: "nzToJp", label: "NZ→日本" },
  { key: "jpToAu", label: "日本→豪州" },
  { key: "jpToCa", label: "日本→カナダ" },
  { key: "minAmount", label: "最低送金額" },
  { key: "maxAmount", label: "送金上限" },
  { key: "fee", label: "手数料", important: true },
  { key: "rate", label: "為替レート", important: true },
  { key: "speed", label: "着金速度", important: true },
  { key: "bankTransfer", label: "銀行送金" },
  { key: "debitCard", label: "デビットカード" },
  { key: "creditCard", label: "クレジットカード" },
  { key: "app", label: "アプリ" },
  { key: "japaneseSupport", label: "日本語対応" },
  { key: "identityCheck", label: "本人確認" },
];

export const moneyTransferRecommendations: PartnerRecommendation[] = [
  {
    title: "生活費を送りたい人向け",
    description: "手数料、着金速度、アプリの使いやすさをまとめて確認します。",
    filterKey: "purpose_living",
  },
  {
    title: "初期費用・家賃向け",
    description: "まとまった金額を送る前に、上限や為替レートを比較したい人向けです。",
    filterKey: "purpose_initial",
  },
  {
    title: "早く送りたい人向け",
    description: "即日から1営業日目安の選択肢を中心に確認します。",
    filterKey: "speed_same_day",
  },
  {
    title: "アプリで管理したい人向け",
    description: "スマホで手続き、本人確認、履歴確認をしやすいサービスを比較します。",
    filterKey: "app",
  },
];

export const moneyTransferServices: PartnerService[] = [
  {
    id: "wise-transfer",
    category: "money_transfer",
    name: "Wise",
    countryCode: "GLOBAL",
    serviceType: "海外送金",
    shortDescription:
      "為替レートと手数料を事前に確認しやすく、生活費や初期費用の送金で比較されやすいサービスです。",
    priceNote: "送金額、通貨、支払方法で変わります。",
    keyFeatures: ["手数料が見やすい", "アプリ対応", "銀行口座向け"],
    recommendedFor: ["生活費", "初期費用", "少額送金", "アプリ管理"],
    cautions: ["本人確認、送金上限、通貨ごとの手数料を確認してください。"],
    comparison: {
      coverage: "グローバル",
      jpToNz: true,
      nzToJp: true,
      jpToAu: true,
      jpToCa: true,
      minAmount: "少額から確認可",
      maxAmount: "通貨・本人確認で変動",
      fee: "事前表示で確認しやすい",
      rate: "実勢レート系",
      speed: "数分〜数営業日目安",
      bankTransfer: true,
      debitCard: true,
      creditCard: true,
      app: true,
      japaneseSupport: true,
      identityCheck: "必要",
    },
    officialUrl: "https://wise.com/",
    isAffiliate: false,
    affiliateStatus: "official",
    affiliateNetwork: "official",
    affiliateLink: undefined,
    lastCheckedAt: "2026-06-26",
    filterTags: [
      "country_nz",
      "country_au",
      "country_ca",
      "purpose_living",
      "purpose_initial",
      "purpose_rent",
      "purpose_family",
      "speed_same_day",
      "speed_one_day",
      "app",
      "japanese_support",
    ],
  },
  {
    id: "ofx",
    category: "money_transfer",
    name: "OFX",
    countryCode: "GLOBAL",
    serviceType: "海外送金",
    shortDescription:
      "まとまった金額や為替レートを重視して比較したい人向けの海外送金サービスです。",
    priceNote: "送金額、通貨、レート条件により異なります。",
    keyFeatures: ["高額送金", "為替レート比較", "オンライン手続き"],
    recommendedFor: ["初期費用", "家賃", "まとまった送金"],
    cautions: ["最低送金額、対応通貨、着金先口座条件を確認してください。"],
    comparison: {
      coverage: "グローバル",
      jpToNz: true,
      nzToJp: true,
      jpToAu: true,
      jpToCa: true,
      minAmount: "要確認",
      maxAmount: "高額送金向き",
      fee: "条件により変動",
      rate: "比較向き",
      speed: "1〜数営業日目安",
      bankTransfer: true,
      debitCard: "要確認",
      creditCard: "要確認",
      app: true,
      japaneseSupport: "要確認",
      identityCheck: "必要",
    },
    officialUrl: "https://www.ofx.com/",
    isAffiliate: false,
    affiliateStatus: "official",
    affiliateNetwork: "official",
    lastCheckedAt: "2026-06-26",
    filterTags: [
      "country_nz",
      "country_au",
      "country_ca",
      "purpose_initial",
      "purpose_rent",
      "purpose_tuition",
      "speed_few_days",
      "app",
    ],
  },
  {
    id: "remitly",
    category: "money_transfer",
    name: "Remitly",
    countryCode: "GLOBAL",
    serviceType: "海外送金",
    shortDescription:
      "スピード重視の送金や、アプリから手続きしたい人が比較しやすいサービスです。",
    priceNote: "送金先、速度、支払方法により異なります。",
    keyFeatures: ["スピード選択", "アプリ", "銀行口座向け"],
    recommendedFor: ["生活費", "仕送り", "早めの送金"],
    cautions: ["為替レートと手数料の合計、送金先国の対応状況を確認してください。"],
    comparison: {
      coverage: "複数国",
      jpToNz: "要確認",
      nzToJp: "要確認",
      jpToAu: true,
      jpToCa: true,
      minAmount: "要確認",
      maxAmount: "本人確認で変動",
      fee: "速度・支払方法で変動",
      rate: "要確認",
      speed: "即日〜数営業日目安",
      bankTransfer: true,
      debitCard: true,
      creditCard: true,
      app: true,
      japaneseSupport: "要確認",
      identityCheck: "必要",
    },
    officialUrl: "https://www.remitly.com/",
    isAffiliate: false,
    affiliateStatus: "official",
    affiliateNetwork: "official",
    lastCheckedAt: "2026-06-26",
    filterTags: [
      "country_au",
      "country_ca",
      "purpose_living",
      "purpose_family",
      "speed_same_day",
      "speed_one_day",
      "app",
    ],
  },
  {
    id: "western-union",
    category: "money_transfer",
    name: "Western Union",
    countryCode: "GLOBAL",
    serviceType: "海外送金",
    shortDescription:
      "オンライン送金に加えて、国や地域によって店舗・現金受取も比較できる大手サービスです。",
    priceNote: "送金方法、国、金額により変わります。",
    keyFeatures: ["店舗網", "現金受取", "オンライン"],
    recommendedFor: ["仕送り", "早めの送金", "現金受取の確認"],
    cautions: ["手数料と為替レートを合計で確認してください。"],
    comparison: {
      coverage: "グローバル",
      jpToNz: true,
      nzToJp: true,
      jpToAu: true,
      jpToCa: true,
      minAmount: "要確認",
      maxAmount: "国・支払方法で変動",
      fee: "条件により変動",
      rate: "要確認",
      speed: "即日〜数営業日目安",
      bankTransfer: true,
      debitCard: true,
      creditCard: true,
      app: true,
      japaneseSupport: true,
      identityCheck: "必要",
    },
    officialUrl: "https://www.westernunion.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-26",
    filterTags: [
      "country_nz",
      "country_au",
      "country_ca",
      "purpose_family",
      "speed_same_day",
      "speed_one_day",
      "app",
      "japanese_support",
    ],
  },
  {
    id: "xe-money-transfer",
    category: "money_transfer",
    name: "XE Money Transfer",
    countryCode: "GLOBAL",
    serviceType: "海外送金",
    shortDescription:
      "為替レート確認と海外送金をまとめて比較したい人向けのサービスです。",
    priceNote: "送金額、通貨ペア、支払方法で変わります。",
    keyFeatures: ["為替レート", "送金", "アプリ"],
    recommendedFor: ["為替比較", "初期費用", "家賃"],
    cautions: ["着金日数、本人確認、対象国を確認してください。"],
    comparison: {
      coverage: "グローバル",
      jpToNz: true,
      nzToJp: true,
      jpToAu: true,
      jpToCa: true,
      minAmount: "要確認",
      maxAmount: "要確認",
      fee: "要確認",
      rate: "比較向き",
      speed: "数分〜数営業日目安",
      bankTransfer: true,
      debitCard: true,
      creditCard: "要確認",
      app: true,
      japaneseSupport: "要確認",
      identityCheck: "必要",
    },
    officialUrl: "https://www.xe.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-26",
    filterTags: [
      "country_nz",
      "country_au",
      "country_ca",
      "purpose_initial",
      "purpose_rent",
      "speed_one_day",
      "speed_few_days",
      "app",
    ],
  },
  {
    id: "paysend",
    category: "money_transfer",
    name: "Paysend",
    countryCode: "GLOBAL",
    serviceType: "海外送金",
    shortDescription:
      "カード送金やアプリでの手続きを比較したい人向けの送金サービスです。",
    priceNote: "送金先、カード種別、通貨により異なります。",
    keyFeatures: ["カード送金", "アプリ", "少額送金"],
    recommendedFor: ["生活費", "少額送金", "アプリ管理"],
    cautions: ["日本発・NZ宛の対応状況とカード手数料を確認してください。"],
    comparison: {
      coverage: "複数国",
      jpToNz: "要確認",
      nzToJp: "要確認",
      jpToAu: "要確認",
      jpToCa: "要確認",
      minAmount: "要確認",
      maxAmount: "要確認",
      fee: "要確認",
      rate: "要確認",
      speed: "即日〜数営業日目安",
      bankTransfer: true,
      debitCard: true,
      creditCard: true,
      app: true,
      japaneseSupport: "要確認",
      identityCheck: "必要",
    },
    officialUrl: "https://paysend.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-26",
    filterTags: ["purpose_living", "speed_same_day", "app"],
  },
  {
    id: "revolut",
    category: "money_transfer",
    name: "Revolut",
    countryCode: "GLOBAL",
    serviceType: "海外送金・マルチ通貨",
    shortDescription:
      "マルチ通貨管理や海外生活中の支払いと合わせて送金を比較したい人向けです。",
    priceNote: "プラン、通貨、曜日、送金方法により異なります。",
    keyFeatures: ["マルチ通貨", "アプリ", "カード"],
    recommendedFor: ["生活費", "複数通貨管理", "アプリ管理"],
    cautions: ["居住国、本人確認、利用可能な機能を確認してください。"],
    comparison: {
      coverage: "複数国",
      jpToNz: "要確認",
      nzToJp: "要確認",
      jpToAu: "要確認",
      jpToCa: "要確認",
      minAmount: "要確認",
      maxAmount: "プランで変動",
      fee: "プラン・条件で変動",
      rate: "要確認",
      speed: "即日〜数営業日目安",
      bankTransfer: true,
      debitCard: true,
      creditCard: "要確認",
      app: true,
      japaneseSupport: "要確認",
      identityCheck: "必要",
    },
    officialUrl: "https://www.revolut.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-26",
    filterTags: ["purpose_living", "speed_one_day", "app"],
  },
  {
    id: "currencyfair",
    category: "money_transfer",
    name: "CurrencyFair",
    countryCode: "GLOBAL",
    serviceType: "海外送金",
    shortDescription:
      "海外送金と為替レートを比較しながら、銀行口座向け送金を検討できます。",
    priceNote: "送金額、通貨、送金方法で変わります。",
    keyFeatures: ["為替比較", "銀行送金", "オンライン"],
    recommendedFor: ["初期費用", "家賃", "まとまった送金"],
    cautions: ["日本発・NZ宛の対応、最低送金額、着金日数を確認してください。"],
    comparison: {
      coverage: "複数国",
      jpToNz: "要確認",
      nzToJp: true,
      jpToAu: true,
      jpToCa: true,
      minAmount: "要確認",
      maxAmount: "要確認",
      fee: "要確認",
      rate: "比較向き",
      speed: "数営業日目安",
      bankTransfer: true,
      debitCard: "要確認",
      creditCard: "要確認",
      app: true,
      japaneseSupport: false,
      identityCheck: "必要",
    },
    officialUrl: "https://www.currencyfair.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    lastCheckedAt: "2026-06-26",
    filterTags: [
      "country_au",
      "country_ca",
      "purpose_initial",
      "purpose_rent",
      "speed_few_days",
      "app",
    ],
  },
];
