import type {
  PartnerComparisonField,
  PartnerFilter,
  PartnerRecommendation,
  PartnerService,
} from "./types";

export const studyAgencyFilters: PartnerFilter[] = [
  { key: "nz", label: "NZ" },
  { key: "au", label: "AU" },
  { key: "ca", label: "CA" },
  { key: "working_holiday", label: "ワーホリ" },
  { key: "language_school", label: "語学学校" },
  { key: "job_support", label: "仕事探し" },
  { key: "housing_support", label: "住居探し" },
  { key: "local_support", label: "現地サポート" },
  { key: "free_consultation", label: "無料相談" },
  { key: "line_consultation", label: "LINE相談" },
];

export const studyAgencyComparisonFields: PartnerComparisonField[] = [
  { key: "nzSupport", label: "NZ対応", important: true },
  { key: "auSupport", label: "AU対応" },
  { key: "caSupport", label: "CA対応" },
  { key: "workingHolidaySupport", label: "ワーホリ対応", important: true },
  { key: "languageSchoolPlacement", label: "語学学校紹介", important: true },
  { key: "visaConsultation", label: "ビザ相談" },
  { key: "jobSearchSupport", label: "仕事探しサポート" },
  { key: "housingSupport", label: "住居サポート" },
  { key: "localSupport", label: "現地サポート" },
  { key: "preDepartureSupport", label: "出発前サポート" },
  { key: "freeConsultation", label: "無料相談", important: true },
  { key: "onlineConsultation", label: "オンライン相談" },
  { key: "lineConsultation", label: "LINE相談" },
  { key: "feeNote", label: "手数料", important: true },
  { key: "reviewNote", label: "口コミ" },
];

export const studyAgencyRecommendations: PartnerRecommendation[] = [
  {
    title: "初心者向け",
    description:
      "留学やワーホリ準備が初めてで、出発前の相談や学校選びをまとめて確認したい人向けです。",
    filterKey: "free_consultation",
  },
  {
    title: "ワーホリ向け",
    description:
      "ワーホリ制度、語学学校、現地生活準備をまとめて相談したい人向けです。",
    filterKey: "working_holiday",
  },
  {
    title: "仕事探し重視",
    description:
      "履歴書、面接、仕事探しの情報提供や現地サポートの有無を確認したい人向けです。",
    filterKey: "job_support",
  },
  {
    title: "語学学校重視",
    description:
      "複数の語学学校やコースを比較し、学費やサポート内容を確認したい人向けです。",
    filterKey: "language_school",
  },
  {
    title: "現地サポート重視",
    description:
      "到着後の生活相談、現地オフィス、トラブル時の相談先を重視したい人向けです。",
    filterKey: "local_support",
  },
];

export const studyAgencyServices: PartnerService[] = [
  {
    id: "school-with",
    category: "study_agency",
    name: "School With",
    countryCode: "GLOBAL",
    serviceType: "留学エージェント",
    shortDescription:
      "語学学校や留学先の比較情報を確認しながら、オンライン相談を検討できるサービスです。",
    priceNote: "相談内容、学校、申込条件により変わります。",
    keyFeatures: ["学校比較", "オンライン相談", "口コミ"],
    recommendedFor: ["初心者", "語学学校比較", "情報収集"],
    cautions: ["紹介対象国、手数料、サポート範囲を公式サイトで確認してください。"],
    comparison: {
      nzSupport: true,
      auSupport: true,
      caSupport: true,
      workingHolidaySupport: true,
      languageSchoolPlacement: true,
      visaConsultation: "depends",
      jobSearchSupport: "depends",
      housingSupport: "depends",
      localSupport: "depends",
      preDepartureSupport: true,
      freeConsultation: true,
      onlineConsultation: true,
      lineConsultation: "depends",
      feeNote: "要確認",
      reviewNote: "口コミ情報あり",
    },
    officialUrl: "https://schoolwith.me/",
    isAffiliate: false,
    affiliateStatus: "none",
    affiliateLink: undefined,
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["nz", "au", "ca", "working_holiday", "language_school", "free_consultation"],
  },
  {
    id: "smaryu",
    category: "study_agency",
    name: "スマ留",
    countryCode: "GLOBAL",
    serviceType: "留学エージェント",
    shortDescription:
      "費用を抑えた留学プランやオンライン相談を確認できる留学エージェントです。",
    priceNote: "プラン、国、学校、期間で変わります。",
    keyFeatures: ["費用比較", "無料相談", "オンライン相談"],
    recommendedFor: ["初心者", "費用重視", "語学学校"],
    cautions: ["料金に含まれる内容、現地サポート、追加費用を確認してください。"],
    comparison: {
      nzSupport: true,
      auSupport: true,
      caSupport: true,
      workingHolidaySupport: true,
      languageSchoolPlacement: true,
      visaConsultation: "depends",
      jobSearchSupport: "depends",
      housingSupport: true,
      localSupport: "depends",
      preDepartureSupport: true,
      freeConsultation: true,
      onlineConsultation: true,
      lineConsultation: true,
      feeNote: "要確認",
      reviewNote: "要確認",
    },
    officialUrl: "https://smaryu.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    affiliateLink: undefined,
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["nz", "au", "ca", "working_holiday", "language_school", "housing_support", "free_consultation", "line_consultation"],
  },
  {
    id: "ef",
    category: "study_agency",
    name: "EF",
    countryCode: "GLOBAL",
    serviceType: "語学留学・教育機関",
    shortDescription:
      "世界各地の語学留学プログラムを確認できるグローバル教育機関です。",
    priceNote: "国、都市、コース、期間で変わります。",
    keyFeatures: ["語学留学", "グローバル", "長期・短期"],
    recommendedFor: ["語学学校重視", "長期留学", "多国籍環境"],
    cautions: ["ワーホリ支援ではなく語学留学中心のため、目的に合うか確認してください。"],
    comparison: {
      nzSupport: "depends",
      auSupport: true,
      caSupport: true,
      workingHolidaySupport: "depends",
      languageSchoolPlacement: true,
      visaConsultation: "depends",
      jobSearchSupport: false,
      housingSupport: true,
      localSupport: true,
      preDepartureSupport: true,
      freeConsultation: true,
      onlineConsultation: true,
      lineConsultation: "depends",
      feeNote: "要確認",
      reviewNote: "要確認",
    },
    officialUrl: "https://www.efjapan.co.jp/",
    isAffiliate: false,
    affiliateStatus: "none",
    affiliateLink: undefined,
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["au", "ca", "language_school", "housing_support", "local_support", "free_consultation"],
  },
  {
    id: "iss-ryugaku-life",
    category: "study_agency",
    name: "ISS留学ライフ",
    countryCode: "GLOBAL",
    serviceType: "留学エージェント",
    shortDescription:
      "留学相談、語学学校紹介、出発前サポートを確認できる留学エージェントです。",
    priceNote: "プラン、学校、サポート内容で変わります。",
    keyFeatures: ["無料相談", "語学学校", "出発前サポート"],
    recommendedFor: ["初心者", "語学学校重視", "出発前準備"],
    cautions: ["無料範囲、有料サポート、紹介学校を確認してください。"],
    comparison: {
      nzSupport: true,
      auSupport: true,
      caSupport: true,
      workingHolidaySupport: true,
      languageSchoolPlacement: true,
      visaConsultation: "depends",
      jobSearchSupport: "depends",
      housingSupport: true,
      localSupport: "depends",
      preDepartureSupport: true,
      freeConsultation: true,
      onlineConsultation: true,
      lineConsultation: "depends",
      feeNote: "要確認",
      reviewNote: "要確認",
    },
    officialUrl: "https://www.iss-ryugakulife.com/",
    isAffiliate: false,
    affiliateStatus: "none",
    affiliateLink: undefined,
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["nz", "au", "ca", "working_holiday", "language_school", "housing_support", "free_consultation"],
  },
  {
    id: "ryugaku-journal",
    category: "study_agency",
    name: "留学ジャーナル",
    countryCode: "GLOBAL",
    serviceType: "留学エージェント",
    shortDescription:
      "長年の留学相談実績があり、国別・目的別の留学相談を確認できます。",
    priceNote: "国、学校、期間、サポート内容で変わります。",
    keyFeatures: ["留学相談", "国別サポート", "学校紹介"],
    recommendedFor: ["初心者", "語学学校重視", "長期検討"],
    cautions: ["相談内容、手数料、サポート範囲を事前に確認してください。"],
    comparison: {
      nzSupport: true,
      auSupport: true,
      caSupport: true,
      workingHolidaySupport: true,
      languageSchoolPlacement: true,
      visaConsultation: "depends",
      jobSearchSupport: "depends",
      housingSupport: true,
      localSupport: "depends",
      preDepartureSupport: true,
      freeConsultation: true,
      onlineConsultation: true,
      lineConsultation: "depends",
      feeNote: "要確認",
      reviewNote: "要確認",
    },
    officialUrl: "https://www.ryugaku.co.jp/",
    isAffiliate: false,
    affiliateStatus: "none",
    affiliateLink: undefined,
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["nz", "au", "ca", "working_holiday", "language_school", "housing_support", "free_consultation"],
  },
  {
    id: "last-resort",
    category: "study_agency",
    name: "ラストリゾート",
    countryCode: "GLOBAL",
    serviceType: "留学・ワーホリエージェント",
    shortDescription:
      "ワーホリ、語学留学、現地サポートを確認できる留学エージェントです。",
    priceNote: "プログラム、サポート内容、国で変わります。",
    keyFeatures: ["ワーホリ", "現地サポート", "無料相談"],
    recommendedFor: ["ワーホリ向け", "現地サポート重視", "初心者"],
    cautions: ["現地サポートの対象都市、内容、費用を確認してください。"],
    comparison: {
      nzSupport: true,
      auSupport: true,
      caSupport: true,
      workingHolidaySupport: true,
      languageSchoolPlacement: true,
      visaConsultation: "depends",
      jobSearchSupport: true,
      housingSupport: true,
      localSupport: true,
      preDepartureSupport: true,
      freeConsultation: true,
      onlineConsultation: true,
      lineConsultation: "depends",
      feeNote: "要確認",
      reviewNote: "要確認",
    },
    officialUrl: "https://www.lastresort.co.jp/",
    isAffiliate: false,
    affiliateStatus: "none",
    affiliateLink: undefined,
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["nz", "au", "ca", "working_holiday", "language_school", "job_support", "housing_support", "local_support", "free_consultation"],
  },
  {
    id: "iae-global",
    category: "study_agency",
    name: "iae GLOBAL",
    countryCode: "GLOBAL",
    serviceType: "留学エージェント",
    shortDescription:
      "世界各国の学校紹介や留学相談を確認できるグローバル留学エージェントです。",
    priceNote: "学校、国、申込内容で変わります。",
    keyFeatures: ["学校紹介", "グローバル", "無料相談"],
    recommendedFor: ["語学学校重視", "多国籍の選択肢", "オンライン相談"],
    cautions: ["対応国、紹介学校、手数料、サポート範囲を確認してください。"],
    comparison: {
      nzSupport: true,
      auSupport: true,
      caSupport: true,
      workingHolidaySupport: "depends",
      languageSchoolPlacement: true,
      visaConsultation: "depends",
      jobSearchSupport: "depends",
      housingSupport: "depends",
      localSupport: "depends",
      preDepartureSupport: true,
      freeConsultation: true,
      onlineConsultation: true,
      lineConsultation: "depends",
      feeNote: "要確認",
      reviewNote: "要確認",
    },
    officialUrl: "https://iae-ryugaku.net/",
    isAffiliate: false,
    affiliateStatus: "none",
    affiliateLink: undefined,
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["nz", "au", "ca", "language_school", "free_consultation"],
  },
  {
    id: "successful-study-abroad",
    category: "study_agency",
    name: "成功する留学",
    countryCode: "GLOBAL",
    serviceType: "留学エージェント",
    shortDescription:
      "留学相談、語学学校紹介、国別サポートを確認できる留学エージェントです。",
    priceNote: "国、学校、期間、サポート内容で変わります。",
    keyFeatures: ["留学相談", "学校紹介", "ワーホリ"],
    recommendedFor: ["初心者", "ワーホリ向け", "語学学校重視"],
    cautions: ["相談範囲、手数料、紹介学校、現地サポートを確認してください。"],
    comparison: {
      nzSupport: true,
      auSupport: true,
      caSupport: true,
      workingHolidaySupport: true,
      languageSchoolPlacement: true,
      visaConsultation: "depends",
      jobSearchSupport: "depends",
      housingSupport: true,
      localSupport: "depends",
      preDepartureSupport: true,
      freeConsultation: true,
      onlineConsultation: true,
      lineConsultation: "depends",
      feeNote: "要確認",
      reviewNote: "要確認",
    },
    officialUrl: "https://www.studyabroad.co.jp/",
    isAffiliate: false,
    affiliateStatus: "none",
    affiliateLink: undefined,
    directAdStatus: "not_contacted",
    lastCheckedAt: "2026-06-28",
    filterTags: ["nz", "au", "ca", "working_holiday", "language_school", "housing_support", "free_consultation"],
  },
];
