export type Property = {
  id: string;
  user_id?: string;
  title: string;
  url?: string | null;
  location: string | null;
  location_master_id?: string | null;
  region_normalized?: string | null;
  territorial_authority_normalized?: string | null;
  major_name_normalized?: string | null;
  suburb_locality_normalized?: string | null;
  address: string | null;
  rent_weekly: number | null;
  bedrooms?: number | null;
  bathrooms?: number | null;
  parking_spaces?: number | null;
  available_from?: string | null;
  pets_allowed?: boolean | null;
  smoking_allowed?: boolean | null;
  utilities_included?: boolean | null;
  bills_included?: boolean | null;
  image_urls?: string[] | null;
  status: string | null;
  latitude: number | null;
  longitude: number | null;
};
